### ISSUE TITLE
Error when opening on elementary os juno

### ISSUE THREAD

**Issue by rizkyramadhan** [akiraux/Akira#120]
akira: symbol lookup error: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined symbol: hb_font_funcs_set_variation_glyph_func

**Comment by Philip-Scott** [comment]
How/where did you install from? You may be missing a library :) Try running `sudo apt install libpangoft2-1.0-0`

**Comment by rizkyramadhan** [comment]
it’s already installed, but still throw same error.

**Comment by Philip-Scott** [comment]
In this case, it's the appimage's fault that it's not working. AppImages must include all the app's dependencies or else it wont run :) Furthermore I'm closing this in favor of #3 since we still don't have an official appimage build
