### ISSUE TITLE
Did Anybody try to compile it on Ubuntu 18.10

### ISSUE THREAD

**Issue by canewsin** [akiraux/Akira#128]
I was trying from 4 complete days not able to compile there is some error is always thrown

**Comment by Philip-Scott** [comment]
And what error is that? It's easier to know what's possibly wrong I'd you share the terminal output with us :)

Keep in mind that a new version of Ubuntu also has new versions of libraries, which is why we want to release a flatpak package of the app

**Comment by canewsin** [comment]
@Philip-Scott 

`src/meson.build:19:0: ERROR:  Invalid version of dependency, need 'granite' ['>= 5.2.0'] found '5.1.0'.`

Ubuntu repo has only 5.1.0 granite 
I tried to compile granite some other error related to that repo and so on..
Is any one successfully compiled granite for Ubuntu 18.10 or 

when i try to downgrade to to use granite 5.1.0 is it throws error may be
app uses elements in granite 5.2.0 
Is there an old repo that uses 5.1.0

**Comment by canewsin** [comment]
could you share a screenshot of current build with some elements drawn because i used flatpak and able to open app i felt it is not fully compiled or

**Comment by albfan** [comment]
You need to build granite 5.2.0 on Ubuntu. That's why we suggest to use flatpak (sandboxing)
Why you "feel" it is not fully compiled?

**Comment by Philip-Scott** [comment]
The app is still a WIP and not ready to be used. Thats's probably why you feel that it is not "fully compiled" 

The homepage (https://github.com/akiraux/Akira) says `AKIRA IS CURRENTLY IN EARLY DEVELOPMENT, NOT READY TO BE USED!` :wink:

**Comment by canewsin** [comment]
Ok Good for Development, I  also started to make prototyping tool from scratch similar to Adobe XD because i just trying ubuntu from 15 days i missed xd alot so i start developing that tool ,Best of luck for your development
