### ISSUE TITLE
AppImage on GitHub Releases is outdated

### ISSUE THREAD

**Issue by probonopd** [akiraux/Akira#131]
The AppImage on GitHub Releases is outdated, please upload a new one. It would be best to use Travis CI to do continuous builds.

**Comment by bilelmoussaoui** [comment]
We didn't release any new release for now. The appimage is not officially supported neither. We will discuss this later once we are closer to an alpha/beta release.

**Comment by bilelmoussaoui** [comment]
This is a duplicate of https://github.com/akiraux/Akira/issues/3. I don't really see a reason for opening a new issue here.
