### ISSUE TITLE
Compile issue on Arch Linux - libarchive

### ISSUE THREAD

**Issue by gdelazzari** [akiraux/Akira#137]
- Akira Version: master @ 1f976d41eeae7b310c66333ad8fbc029ee1d2206
- OS Info: Arch Linux rolling release

I'm trying to compile on Arch Linux, meson finds all the dependencies but it seems I have a different version of the Archive Vala package/library (sorry, I know almost nothing about Vala...) since the function signatures are different. What version of libarchive are you using? The documentation on [Valadoc](https://valadoc.org/libarchive/Archive.html) show indeed that the code is using the right parameters for the function calls, but that doesn't seem to match with what I have on my system.

pacman says that libarchive is at 3.3.3-1

Anyone can help me figure it out? Thanks!

```console
../src/FileFormat/ZipArchiveHandler.vala:268.20-268.86: error: 1 extra arguments for `Archive.Result Archive.Read.read_data_block (out weak uint8[], out Archive.int64_t)'
            while (archive.read_data_block (out buffer, out buffer_length, out offset) == Archive.Result.OK) {
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/FileFormat/ZipArchiveHandler.vala:269.49-269.54: error: Argument 1: Cannot convert from `void*' to `unowned uint8[]'
                if (extractor.write_data_block (buffer, buffer_length, offset) != Archive.Result.OK) {
                                                ^^^^^^
../src/FileFormat/ZipArchiveHandler.vala:269.21-269.78: error: 1 extra arguments for `ssize_t Archive.Write.write_data_block (uint8[], Archive.int64_t)'
                if (extractor.write_data_block (buffer, buffer_length, offset) != Archive.Result.OK) {
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/FileFormat/ZipArchiveHandler.vala:319.37-319.57: error: Argument 1: Cannot convert from `int64' to `Archive.int64_t'
                    entry.set_size (file_info.get_size ());
                                    ^^^^^^^^^^^^^^^^^^^^^
../src/FileFormat/ZipArchiveHandler.vala:321.37-321.40: error: Argument 1: Cannot convert from `int' to `Archive.FileType'
                    entry.set_perm (0644);
                                    ^^^^
../src/FileFormat/ZipArchiveHandler.vala:336.25-336.63: error: 1 extra arguments for `ssize_t Archive.Write.write_data (uint8[])'
                        archive.write_data (buffer, bytes_read);
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 6 error(s), 0 warning(s)
ninja: build stopped: subcommand failed.
```

**Comment by albfan** [comment]
Hi, I'm on arch linux too.

    $ vala --version
    Vala 0.44.2

It seems related with improvements on vala 0.44.2

Something like https://github.com/akiraux/Akira/tree/wip/albfan/vala-0.44.2 should be merged at some point.

By now:

```
$ flatpak run --command=bash org.gnome.Sdk//3.30 
[📦 org.gnome.Sdk ~]$ vala --version
Vala 0.42.5

#simpler but more obscure:
$ flatpak run --command=vala org.gnome.Sdk --version
Vala 0.44.1.43-ddf82
```
We shouldn't be affected.

We recommend to build from flatpak to isolate from these problems. If you want to use command line:

```
$ flatpak-builder --ccache --force-clean --stop-at=akira flatpak-build build-aux/flatpak/com.github.akiraux.akira.json
$ flatpak build flatpak-build meson --prefix=/app --libdir=lib --buildtype=plain build-meson
$ flatpak build flatpak-build ninja -C build-meson
$ flatpak build flatpak-build ninja -C build-meson install
$ flatpak-builder --run flatpak-build build-aux/flatpak/com.github.akiraux.akira.json com.github.akiraux.akira
```
should be enough to develop on your local checkout

**Comment by Alecaddd** [comment]
Closing this as we're not supporting specific platforms for now and we will soon release a flatpak for development.

**Comment by albfan** [comment]
Agreed with @Alecaddd. Anyway https://github.com/akiraux/Akira/tree/wip/albfan/vala-0.44.2 is now building conditional depending on vala. Anyway there're more fixes on libarchive.vapi comming in next releases:

https://gitlab.gnome.org/GNOME/vala/commit/b8e1a4e591fde375dc46c72d27ed31e2d06ef072

So let's wait for vala to upgrade in all platforms before face this

**Comment by vallsv** [comment]
Same problem on Debian 10 (which only provide vala 0.42.5 or 0.44.3)
The branch provided by @albfan i still mergeable without problem.
Thanks a lot.

**Comment by aissat** [comment]
i fixed this prbm
