### ISSUE TITLE
When the akira app stable release?

### ISSUE THREAD

**Issue by dewaadiperdana** [akiraux/Akira#147]
Thanks to akira team for building this software, i have installed on my machine, but slightly different from the screenshot you provide, i have a plan on designing a mobile app using akira but if i may ask, when the akira app stable release?? thanks

**Comment by Alecaddd** [comment]
Thanks for your interest in Akira.
We don't know when a first stable version will be released. We're working as much as we can during weekends or after work, and we're trying to push it as much as we can.
Once we're close to having something almost ready, we will announce an official date.

**Comment by dewaadiperdana** [comment]
I do build the akira app from the source code, on my machine. Im using Linux Mint 19 Tessa, but the app look like this
![Screenshot_2019-04-26_12-57-36](https://user-images.githubusercontent.com/11770425/56784427-faf44500-6822-11e9-9c6f-a82ad3e506af.png)

And i can't do much with the tools provided by the app

**Comment by albfan** [comment]
You better build Akira with GNOME Builder IDE. It will use flatpak (a sandbox) a you will get the native build as if you where in elementary OS). Basic features you expected are almost ready to land, you just need to wait a bit more.

**Comment by Alecaddd** [comment]
Like Alberto said, build it using flatpak inside Gnome Builder to get the proper UI, icons, and theme.
Anyway, I don't want to be rude but it's written pretty clearly and all caps on the readme file.

**AKIRA IS CURRENTLY IN EARLY DEVELOPMENT, NOT READY TO BE USED!**

You can't expect a software to be usable if it hasn't been released anywhere yet.

**Comment by dewaadiperdana** [comment]
Ok, thank you for your answers

**Comment by ertoorule** [comment]
When I look at your attitude, I see Alexsander Adam! i mean ceo of gravit designer!
