### ISSUE TITLE
The possibility to build a official website to the project

### ISSUE THREAD

**Issue by nazarepiedady** [akiraux/Akira#148]
## Expected Behavior
What's up, firstful sorry for my english grammar, I don't speak english fluently yet, but I'd like to contribute with the project building a website to share and meeting with users of this product, but I will need some help to do this. In the last days I was dedicated to find people to support the project in some groups about development, ux, ui on facebook and telegram, but I want to do more.

**Comment by Alecaddd** [comment]
Hi, thanks for your interest in Akira.
The repository for the website is already available, based on NuxtJS: https://github.com/akiraux/website

This is the design of the website: https://www.patreon.com/posts/akira-website-25444526

Feel free to contribute to that repo. For now, we're focused on coding the actual app and the website will come later down the line.
Cheers

**Comment by bilelmoussaoui** [comment]
As @Alecaddd mentioned, we have a repository for the website and we also have a mockup for it. We would accept any help, if you have any concerns or ideas, please open that in the correct repository akiraux/website. Thanks!
