### ISSUE TITLE
Build a solid Canvas Library! 

### ISSUE THREAD

**Issue by Alecaddd** [akiraux/Akira#15]
Follow on-going project: https://github.com/Philip-Scott/libgtkcanvas

**Comment by harisvsulaiman** [comment]
Any update on this?

**Comment by Alecaddd** [comment]
It's in progress. I'm currently focusing on the Layers panel until the end of the week. From Monday, 100% of the focus will go towards the canvas

**Comment by aberba** [comment]
Hey @Alecaddd, found this https://github.com/meetalva/alva. Seem like some inspiration.

**Comment by Alecaddd** [comment]
Closing this as a dedicated Repo has been created for it.
https://github.com/akiraux/interactive-goocanvas
