### ISSUE TITLE
Create the Style Panel

### ISSUE THREAD

**Issue by Alecaddd** [akiraux/Akira#152]
## Style Panel
A panel that lists all the properties and styles of a specific objects.
As a first implementation we will only offer the border radius styling option, but later down the line this panel will be used to list shared styles, and other attributes.

## Screenshots
![style-panel](https://user-images.githubusercontent.com/2527103/56871748-a5609980-69d6-11e9-8a59-61a802253d90.png)

The "gear" icon will reveal extra options for the border radius attribute.
![style-panel-open](https://user-images.githubusercontent.com/2527103/56871754-ab567a80-69d6-11e9-9945-c4d508ff7be2.png)

**Comment by bilelmoussaoui** [comment]
The panel must be on the left or the right?

**Comment by Alecaddd** [comment]
@bilelmoussaoui left panel, as you can see I added this issue to the `Shape Option Panel` project.
This should be above the filling option.

**Comment by bilelmoussaoui** [comment]
My bad, I should have looked closer.
