### ISSUE TITLE
Change mouse cursor to proper icon when hovering rotation nob

### ISSUE THREAD

**Issue by Alecaddd** [akiraux/Akira#161]
It doesn't seem to be available out of the box a `rotate` cursor in GTK. Right now, we're changing it to a boxed one just to show something different.
How do we tackle this? Can we use a custom SVG for the cursor?

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2527103/57575578-ed81b200-7401-11e9-94b0-9153e405b96b.gif)

**Comment by albfan** [comment]
- Can a GDK Pixbuf be rotated by something less than 90 degrees? https://stackoverflow.com/a/39130357/848072
- Custom Gtk pixbuf cursor https://stackoverflow.com/q/37204591/848072

**Comment by flurick** [comment]
Was into the code on this issue but it looks like it will soon be solved in [goocanvas](https://github.com/akiraux/interactive-goocanvas/issues/13), so help found?

**Comment by Alecaddd** [comment]
lol, that's me, I opened that message on the canvas :wink: 
I'll fix this later
