### ISSUE TITLE
Use libdazzle to handle multipaned

### ISSUE THREAD

**Issue by bilelmoussaoui** [akiraux/Akira#162]
Currently, we are using two Gtk.Paned to have the left and right sidebar which is not a great way of doing things. Gtk.Paned was made to work with only childs. 

I think using Dazzle.MultiPaned should allow us to have things work better 
https://valadoc.org/libdazzle-1.0/Dazzle.MultiPaned.html

libdazzle, could be great for other widgets too.

**Comment by Alecaddd** [comment]
Uh nice, if it can help us write less code I'm all for it.
Feel free to make a PR so we can review it :+1:

**Comment by raggesilver** [comment]
Beware libdazzle's MultiPaned has awful defaults (not nearly as polished as Gtk.Paned) but it does the trick. It might be easier to use if you guys create a wrapper around it. Also looking at Akira's flatpak manifest I can see libdazzle is not a dependency used in the project, and having an entire library added for a single widget (that you might end up creating a wrapper to) might be a bit overpower.

**Comment by Alecaddd** [comment]
@raggesilver these are really good points.
I never used libdazzle, is there something worth considering other than the multipanel?

**Comment by raggesilver** [comment]
Actually, libdazzle has a Dazzle.Dock (I think) that I've never been able to make work that is in theory what Builder uses to have side panels that can be toggled with animations and resized. If you guys are going to use libdazzle you might consider using that. In the other hand if toggling isn't very important MultiPaned's source is barely 1400 lines of C code. Shouldn't be more than 500 of Vala to implement something similar.

**Comment by Alecaddd** [comment]
I'm closing this as the Gtk.Paned works perfectly for what we need, and we don't want to add an entire new library only for one widget.
