### ISSUE TITLE
[Suggestion] Add a guide about building Akira for Ubuntu

### ISSUE THREAD

**Issue by nisrulz** [akiraux/Akira#174]
The steps in the readme about building Akira from source do not map right away when it comes to Ubuntu distro. Although Akira is being built using elementary OS widgets, it would be really nice to have the guides for building it on Ubuntu (which is the most popular and used distro).

On a side note, I have been trying to build Akira on Ubuntu 18.0.4.2 and it took me some time to get it to build successfully. 

Some issues I found in the process:
- The dependencies listed are not exactly the same as available through Ubuntu launchpad.
   > I had to search and find the right replacement as per Ubuntu
- Whatever I do, I couldn't get `granite` dependency to be updated to version > = 5.2.0. This is not directly evident. I even posted a question on [askUbuntu](https://askubuntu.com/questions/1146301/how-to-install-a-specific-version-of-granite-dependency-on-ubuntu-18-0-4)
   > In the end, I decided to build granite from the source and latest master i.e v5.2.3
- The same issue as above was for installing vala-lint also 
   > I resorted to installing it from source again

In this process, I figured out that a lot of the developers who use Ubuntu like me would tend to encounter this same issue.

So I wrote down simple bash scripts to automate the process and would like to contribute it back to the main repo. 

If this suggestion makes sense, I will go ahead and open a PR with the same. Possibly also add some more documentation around how to step through the build process.

Open to feedback.

**Comment by nisrulz** [comment]
My build scripts are very simple bash scripts, however, I did find out something that would make more sense for the project.

https://github.com/Philip-Scott/Notes-up/wiki/Build-and-Install-on-Ubuntu-and-other-distros

> Although I am not quite sure we need to make it as complex as this.

**Comment by Alecaddd** [comment]
Mh, this could definitely be useful, but I'm not sure how much spotlight we want to give it.
We'd like to encourage devs to use the built-in Flatpak implementation, since it takes care of all the dependencies and makes it as easy as clicking a button in Gnome builder, but I understand everyone can do what they prefer.

I'd see this more as a dedicated section in the Wiki, more than cluttering the readme or adding other files to the repo.
Let's use this issue to write something down which I can later put into the Wiki.

**Comment by nisrulz** [comment]
>  built-in Flatpak implementation, since it takes care of all the dependencies and makes it as easy as clicking a button in Gnome builder

Oh, how do I do that? I mean there is nothing about this anywhere :thinking:  

I literally just followed the readme to build from source but is it actually possible to get it directly from flatpack?

Also, I am quite sure, as developers, everyone needs to build it from source after making changes. So this is actually important, no?

I agree with your point about making it a page in the wiki. This is why I added a link later about how someone else was doing it.

**Comment by Alecaddd** [comment]
@bilelmoussaoui and @albfan can give better direction, and maybe help write a little guide.

For what I know, and if I'm not wrong, if you download the repo on your computer and you load it into GNOME Builder, the `build-aux/flatpak` should be recognized and you can build with a simple click.

Of course, this method doesn't work if you don't use GNOME Builder, that's why I think a broader and in-depth building guide in the Wiki is a good addition.

**Comment by bilelmoussaoui** [comment]
You don't need to do anything special, just open GNOME Builder, open the project and click on Run, it will build it and run it for you.
I don't see a reason for providing a hackish script to build the app on Ubuntu, we can just completely forget to update it later :/

**Comment by nisrulz** [comment]
Got it. I had no idea this is how it works. 

Maybe then we should also have this as part of the wiki page and link it from the Readme. I am against putting everything in the Readme myself, but would really have benefited from having this information up front. So TIL there is an easier way :sweat_smile:

**Comment by bilelmoussaoui** [comment]
Also, Builder knows which module on the flatpak manifest is your app (the latest one on the modules list) so it already builds your local version here; It's not installed, it doesn't interfere with your system, it will never break anything besides maybe crashing Builder :P

**Comment by nisrulz** [comment]
![Screenshot from 2019-05-27 02-18-25](https://user-images.githubusercontent.com/2096087/58388957-d8be3480-8025-11e9-9fb6-c915ce78b20e.png)

I just gave it a try. Looks like it is not as straight forward :disappointed: 

@bilelmoussaoui All valid points, but the script I have isn't at all hackish. As I said it does exactly what is in the readme with proper replacements for dependencies and ofcourse it is a bash script so it will do all the build steps of using meson and ninja.

**Comment by nisrulz** [comment]
The point I wanted to make is, that if there is any specific path to building Akira for development, like the ones you just mentioned then it would be really really nice to have it somewhere. Like me, more people will try their own versions and hit-and-trial methods to get it to work.

**Comment by nisrulz** [comment]
I just tried to install a dependency it was asking and now it does recognize everything, but I am stuck with the below error message inside the Gnome Builder:

```flatpak-builder --arch=x86_64 --ccache --force-clean --disable-updates --disable-download --state-dir /home/nishant/.var/app/org.gnome.Builder/cache/gnome-builder/flatpak-builder --stop-at=akira /home/nishant/.var/app/org.gnome.Builder/cache/gnome-builder/projects/Akira/flatpak/staging/x86_64-master /home/nishant/Documents/workspaces/akiraux/Akira/build-aux/flatpak/com.github.akiraux.akira.json
error: io.elementary.BaseApp/x86_64/juno not installed
Failed to init: Unable to find app io.elementary.BaseApp version juno
```

**Comment by nisrulz** [comment]
For record purpose, anyone who is trying to build from source, here is the script I wrote to build it from source: 

https://gist.github.com/nisrulz/b644898bddf7e336df7457dafa09f77a

> @bilelmoussaoui @albfan maybe take a look at it and provide your feedback whenever you get time.

**Comment by bilelmoussaoui** [comment]
@nisrulz Builder can install SDK for you but not the baseApp. Quick definitions of thoses
GNOME/FreeDesktop/KDE sdk's are like Android Sdk's (you seem to be an android dev)
the baseApp is just a bunch of libraries/models/themes/whatever that's shared by too many apps that putting them on one place is great. So you need to fire up the terminal and do 
```
flatpak install flathub  io.elementary.BaseApp//juno
```

**Comment by bilelmoussaoui** [comment]
@nisrulz for now, we list the dependencies on the README, but in a near future, as elementary also going the Flatpak way, we will just remove these from there as a simple manifest can allow you to hack on the app, install it for tesing purposes or whatever you want. We don't want a user (not a developer) to play with his system and exec commands as a sudoer.

**Comment by nisrulz** [comment]
@bilelmoussaoui everything works now :fireworks:  :smile_cat: 

Thank you for walking me through the steps. I can now run Akira using Gnome Builder. 
I wish this was much clear earlier so that I wouldn't have to fiddle around and find out a way to build it from the source. Would have saved some hours of searching, hit-and-trials for me. 

Thank you once again :)

**Comment by bilelmoussaoui** [comment]
Always happy to help. You can ping me if you need some help GTK/Flatpak/Meson/Akira related stuff. 
I'm going to close this until we get to stage we can put the flatpak details on the README.
Thanks for the suggestion!
