### ISSUE TITLE
If Elementary icons & themes are installed, propose to use it throughout the application

### ISSUE THREAD

**Issue by logarytm** [akiraux/Akira#179]
This is somewhat related to #93. I have the elementary icon & GTK+ themes installed, but I'm on GNOME and using the Adwaita theme. I've installed the app manually through `meson build … && ninja && ninja install`. The idea is, on the first run Akira could prompt me to switch to these themes application-wide. It needn't (and probably shouldn't) be a modal dialog — more like a toast or an information bar at the bottom of the screen (so it does not cover/move the main part of the window).

The upsides:
- The user can choose between respecting the system theme or using the supported/targetted configuration

The downsides:
- It's an interaction orthogonal to the purpose of the application
- It's somewhat a special case scenario
    - as an alternative we could bundle the theme as part of the app package and always propose the switch, not only if it is present in the OS

Alternatives:
- Not doing this and recommending flatpak/snap installation instead (see #93)
- Picking up the style right away if it's available

Mockup (I'm not sure this is the proper UI pattern):

![image](https://user-images.githubusercontent.com/2938672/59552130-40133880-8f83-11e9-8e68-d2dd96a01933.png)

**Comment by bilelmoussaoui** [comment]
No sorry. The theme will be hardcoded on the application itself.

**Comment by albfan** [comment]
@logarytm. I'm on arch Linux and have the elementary theme installed through AUR packages. It works out of the box. Is not your case?

You need to see theme and icons as another Akira dependency. We need to implement our app vision

**Comment by logarytm** [comment]
Sorry, you're right. Turns out I haven't installed the GTK+ theme, but not the icons. I wish you best luck with this awesome project <3

**Comment by NewtronReal** [comment]
Where did you download them? (not for arch)
