### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by DwiWardana** [akiraux/Akira#181]
Hi i think there's you had a typo on [here](https://github.com/akiraux/Akira#-compile) at Note that's not "vala" but "valac"

**Comment by manokara** [comment]
It depends on the distro. On Solus for example, there's `libvala` which has only the library, and `vala` with everything else (compiler, vapis, etc). It could be clarified to something along the lines of "install everything vala related available in your distro".

**Comment by bilelmoussaoui** [comment]
I'm going to remove this list of dependencies as we don't need that anymore. You should just use the Flaptak manifest.
