### ISSUE TITLE
Huge black border in flatpak build

### ISSUE THREAD

**Issue by manokara** [akiraux/Akira#184]
## Normal system build

![image](https://user-images.githubusercontent.com/3709789/60605757-7b3da600-9d90-11e9-9706-7a7643bb5c01.png)

## Flatpak build

![image](https://user-images.githubusercontent.com/3709789/60605833-9dcfbf00-9d90-11e9-8a66-d75a94ce218b.png)

I think this was supposed to be a drop shadow from Elementary's theme. I am using i3wm with a GNOME setup, and compositing enabled with compton. If this was a drop shadow it should've worked?

**Comment by bilelmoussaoui** [comment]
This is due to an issue on the elementary theme. I will try to patch that on the elementary baseApp the the Flatpak package depends on. Will close that here and will let you know once it's fixed.

**Comment by bilelmoussaoui** [comment]
Here's the link of the base app repository in case you want to report that. I will be in front of my computer tomorrow and do that. https://github.com/flathub/io.elementary.BaseApp/issues
