### ISSUE TITLE
Text labels have bad color, text unreadable

### ISSUE THREAD

**Issue by jpcima** [akiraux/Akira#185]
Hi, I have text display issues on Akira which makes working very difficult.

## Expected Behavior
Readable text labels

## Current Behavior
Some text elements are draw in white color over grey or white background, causing these to be difficult or impossible to read.

It's not only text, there are also non-textual drawings which are affected, as seen on the left side bar.

## Steps to Reproduce (for bugs)
Run the program on MATE desktop 1.22.1.
The bug occurs on the initial session of a new user, having default settings.

## Context
There are a few Gtk warnings which I doubt are precisely related to problem, these are:

```
(Akira:4518): Gtk-WARNING **: 20:21:16.027: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.

(Akira:4518): Gtk-WARNING **: 20:21:24.869: GtkGrid 0x55da524a3590 adjusted size vertical min -6 natural -6 must not decrease below min 6 natural 6

(Akira:4518): Gtk-WARNING **: 20:21:24.869: GtkGrid 0x55da524a3590 attempted to adjust its size allocation from -20,12 219x6 to 0,0 194x18. adjust_size_allocation must keep allocation inside original bounds
```

## Screenshots of the Problem
![Capture du 2019-07-08 20-27-08](https://user-images.githubusercontent.com/17614485/60833569-cdcaf800-a1be-11e9-8830-bb730e1b4b7f.png)

## Your Environment (for bugs)
`Linux ext 4.19.57-1-lts #1 SMP Wed Jul 3 16:05:59 CEST 2019 x86_64 GNU/Linux`
Arch Linux

- Akira Version: master 1964762 + [patch for building]( https://github.com/akiraux/Akira/commit/854e0070cc9a3515950540036b34ece48004dee8.patch)
- OS Info: Arch Linux amd64 latest

**Comment by jpcima** [comment]
I've found the problem to be related to css style sheets.

When I removed this property, one of the heading texts is now displaying.
https://github.com/akiraux/Akira/blob/196476233eb5ca148000d29892cea854393b5807/data/css/layout.css#L117

**Comment by Alecaddd** [comment]
Hi, thanks for your interest in Akira, but as we wrote in the readme, this app is still under development and not even an alpha version has been released. Being broken is totally normal.
I suggest to load the repo in Gnome Builder in order to let it use the flatpak manifest and get the proper stylesheet working.
Cheers
