### ISSUE TITLE
Software does not compile

### ISSUE THREAD

**Issue by SpectralMemories** [akiraux/Akira#191]
Commit: master/17e894c6d57e0b62be288f5be5693edb0634716b

## Expected Behavior

Software should compile normally

## Current Behavior
Ninja fails to compile Akira. [Here is the output](https://pastebin.com/e0bDVdrx)
[Meson config output](https://pastebin.com/4K5iez63)

## Possible Solution
Check out the cause of said problem

## Steps to Reproduce (for bugs)

1. Download commit 17e894c6d57e0b62be288f5be5693edb0634716b
2. Run meson build --prefix=/usr --Dprofile=default
3. Run cd build && ninja

## Context
I tried to compile and install Akira

## Screenshots of the Problem
See [terminal output](https://i.imgur.com/9ighQfs.png)

## Your Environment (for bugs)
[Info](https://pastebin.com/uN9npHSd)

I have all the dependencies installed on my system. Vala version:  0.44.6

- Akira Version: Commit 17e894c6d57e0b62be288f5be5693edb0634716b
- OS Info: Arch Linux as of August 16th

Thanks for looking it out

**Comment by Alecaddd** [comment]
This is a well known issue with the version of Vala we're using, which is the one currently supported in the Ubuntu LTS.
Alberto created this WIP branch with compatibility fixes: https://github.com/akiraux/Akira/tree/wip/albfan/vala-0.44.2

**Comment by Alecaddd** [comment]
Here's a patch from Alberto: This happens with Vala 0.44.2+, they changed the signatures of these methods in libarchive. Alberto's patch fixes the build for now.

**Comment by NewtronReal** [comment]
How can I use this patch.

**Comment by albfan** [comment]
Reapply on master and build again

**Comment by NewtronReal** [comment]
> Reapply on master and build again

I can't understand that. In which file I need to apply this code.

**Comment by albfan** [comment]
I discourage to build from source if you need to ask what a patch is and
how to apply.

This patch is in a branch you can rebase easily.

To avoid noise I will remove this comment.

The definitely need a chat to deal with this problems.
