### ISSUE TITLE
meson.build:2:0: ERROR: Could not execute Vala compiler "valac"

### ISSUE THREAD

**Issue by NewtronReal** [akiraux/Akira#192]
Build started at 2019-08-18T20:51:19.187619
Main binary: /usr/bin/python3
Python system: Linux
The Meson build system
Version: 0.51.1
Source dir: /home/newtron/AKIRA/Akira
Build dir: /home/newtron/AKIRA/Akira/build
Build type: native build
Project name: com.github.akiraux.akira
Project version: undefined
No CFLAGS in the environment, not changing global flags.
No LDFLAGS in the environment, not changing global flags.
No CPPFLAGS in the environment, not changing global flags.
Sanity testing C compiler: cc
Is cross compiler: False.
Sanity check compiler command line: cc -pipe -D_FILE_OFFSET_BITS=64 /home/newtron/AKIRA/Akira/build/meson-private/sanitycheckc.c -o /home/newtron/AKIRA/Akira/build/meson-private/sanitycheckc.exe
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /home/newtron/AKIRA/Akira/build/meson-private/sanitycheckc.exe
C compiler for the build machine: cc (gcc 8.3.0 "cc (Ubuntu 8.3.0-6ubuntu1) 8.3.0")

meson.build:2:0: ERROR: Could not execute Vala compiler "valac"
OS : Ubuntu 19.04
Akira Version : undefined

**Comment by NewtronReal** [comment]
How can I fix this issue, please comment

**Comment by rodgomesc** [comment]
Do you have vala compiler in our system?

What is the output of `valac --version` in terminal

**Comment by NewtronReal** [comment]
@rodgomesc thanks. I haven't installed valac.
