### ISSUE TITLE
 Could not generate cargs for gtk+-3.0:

### ISSUE THREAD

**Issue by NewtronReal** [akiraux/Akira#193]
Using cached compile:
Cached command line:  valac /tmp/tmp_thmy1p4/testfile.vala -C 

Code:
 class MesonSanityCheck : Object { }
Cached compiler stdout:
 
Cached compiler stderr:
 
Vala compiler for the host machine: valac (valac 0.44.3)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Pkg-config binary for MachineChoice.HOST is not cached.
Pkg-config binary missing from cross or native file, or env var undefined.
Trying a default pkg-config fallback at pkg-config
Trying pkg-config binary pkg-config for machine MachineChoice.HOST at ['/usr/bin/pkg-config']
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Determining dependency 'gtk+-3.0' with pkg-config executable '/usr/bin/pkg-config'
PKG_CONFIG_PATH: 
Called `/usr/bin/pkg-config --modversion gtk+-3.0` -> 0
3.24.8
PKG_CONFIG_PATH: 
Called `/usr/bin/pkg-config --cflags gtk+-3.0` -> 1

Could not generate cargs for gtk+-3.0:

CMake binary for MachineChoice.HOST is not cached
CMake binary missing from cross or native file, or env var undefined.
Trying a default CMake fallback at cmake
Trying CMake binary cmake for machine MachineChoice.HOST at ['/usr/bin/cmake']
Found CMake: /usr/bin/cmake (3.13.4)
Extracting basic cmake information
Try CMake generator: auto
Called `/usr/bin/cmake --trace-expand .` in /home/newtron/AKIRA/Akira/build/meson-private/cmake_gtk+-3.0 -> 0
  -- Module search paths:    ['/', '/opt', '/usr', '/usr/local']
  -- CMake root:             /usr/share/cmake-3.13
  -- CMake architectures:    ['i386-linux-gnu', 'x86_64-linux-gnu']
  -- CMake lib search paths: ['lib', 'lib32', 'lib64', 'libx32', 'share', 'lib/i386-linux-gnu', 'lib/x86_64-linux-gnu']
Run-time dependency gtk+-3.0 found: NO (tried cmake)

meson.build:16:0: ERROR: Could not generate cargs for gtk+-3.0:

- Akira Version: undefined
- OS Info: Ubuntu  19.04

**Comment by albfan** [comment]
how this issue is related with Akira?

Even, it lacks a proper introduction.

We can reopen if you provide context.
