### ISSUE TITLE
 meson.build:16:0: ERROR: Could not generate cargs for gtk+-3.0:

### ISSUE THREAD

**Issue by NewtronReal** [akiraux/Akira#194]
I have downloaded the zip file given. Extracted it and installed all dependencies. First time I tried to run the meson file without installing gtk3+ libs and it gave me this err. The second time I've installed  gtk3+ lib and it gave me this same error.
Using cached compile:

```
Cached command line: valac /tmp/tmp_thmy1p4/testfile.vala -C

Code:
class MesonSanityCheck : Object { }
Cached compiler stdout:

Cached compiler stderr:

Vala compiler for the host machine: valac (valac 0.44.3)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Pkg-config binary for MachineChoice.HOST is not cached.
Pkg-config binary missing from cross or native file, or env var undefined.
Trying a default pkg-config fallback at pkg-config
Trying pkg-config binary pkg-config for machine MachineChoice.HOST at ['/usr/bin/pkg-config']
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Determining dependency 'gtk+-3.0' with pkg-config executable '/usr/bin/pkg-config'
PKG_CONFIG_PATH:
Called /usr/bin/pkg-config --modversion gtk+-3.0 -> 0
3.24.8
PKG_CONFIG_PATH:
Called /usr/bin/pkg-config --cflags gtk+-3.0 -> 1

Could not generate cargs for gtk+-3.0:

CMake binary for MachineChoice.HOST is not cached
CMake binary missing from cross or native file, or env var undefined.
Trying a default CMake fallback at cmake
Trying CMake binary cmake for machine MachineChoice.HOST at ['/usr/bin/cmake']
Found CMake: /usr/bin/cmake (3.13.4)
Extracting basic cmake information
Try CMake generator: auto
Called /usr/bin/cmake --trace-expand . in /home/newtron/AKIRA/Akira/build/meson-private/cmake_gtk+-3.0 -> 0
-- Module search paths: ['/', '/opt', '/usr', '/usr/local']
-- CMake root: /usr/share/cmake-3.13
-- CMake architectures: ['i386-linux-gnu', 'x86_64-linux-gnu']
-- CMake lib search paths: ['lib', 'lib32', 'lib64', 'libx32', 'share', 'lib/i386-linux-gnu', 'lib/x86_64-linux-gnu']
Run-time dependency gtk+-3.0 found: NO (tried cmake)

meson.build:16:0: ERROR: Could not generate cargs for gtk+-3.0:
```

now I've reopened it with all the actions I've performed. Can anybody please help me?

    Akira Version: undefined
    OS Info: Ubuntu 19.04

**Comment by albfan** [comment]
Devil is in details:

> First time I tried to run the meson file without installing gtk3+ libs and it gave me this err. 

Why would you do that? If gtk is a dep you need to install it.

> The second time I've installed gtk3+ lib and it gave me this same error.

So you didn't install it. Better than say what you did is to show the commands you use. Surely you reinstall the binary package. You need the devel package. That is not an Akira issue, but an Ubuntu one:

https://askubuntu.com/questions/11237/installing-gtk-development-environment

> I would say it is libgtk-3-dev right now

https://packages.ubuntu.com/disco/libgtk-3-dev

We recommend to develop under flatpak or elementary to avoid all this problems.

**Comment by NewtronReal** [comment]
I've tired by installing, updating and reinstalling the package libgtk-3-dev and its dependencies. Unfortunately, none of that were worked for me. Am I missing any dep? I 've installed all thing related to gtk+-3 by this sudo apt install gtk-* command. So what is the actual problem I am facing.

Sorry for my bad English

**Comment by albfan** [comment]
you should show what is theproblem after I install those deps

**Comment by albfan** [comment]
We can reopen if you provide more context. Install libgtk-3-dev is the standard solution for ubuntu
