### ISSUE TITLE
Alpha Release Wishlist

### ISSUE THREAD

**Issue by Alecaddd** [akiraux/Akira#206]
## Setting up expectations for an Alpha release

Here's a list of must-have features for a first release of Akira.
This list is a **Work in Progress** and it can change based on our availability and technical challenges.

### General UI
- [x] All icons can be changed between regular and symbolic from Settings.
- [x] Hide/Show labels underneath Headerbar buttons from Settings.
- [x] Remember side panel sizing in `gsettings`.
- [x] Preview mode with <kbd>CTRL</kbd> + <kbd>.</kbd>.
- [x] Alert dialog before closing if document has been edited and not saved.

### Canvas
- [x] Default Canvas at 100K x 100K pixels.
- [x] Zoom action via Headerbar button and <kbd>CTRL</kbd> + <kbd>+</kbd>/<kbd>CTRL</kbd> + <kbd>-</kbd>
- [x] Zoom action via mouse scroll with <kbd>CTRL</kbd> + <kbd>Scroll</kbd>
- [x] Pan action with mouse middle click and <kbd>Spacebar</kbd> + click and drag.
- [x] Create Artboards.
- ~Shapes should snap to Artboard's edges.~
- ~Click and drag on an empty canvas area to select multiple shapes.~

### Shapes
- [x] Manage default fill and border color in Settings.
- [x] Add Rectangle.
- [x] Add Ellipse.
- [x] Import/Add Image.
- [x] Control shapes order via Headerbar buttons.
- [x] Control Position and sizing via Transform Panel.
- [x] Lock resize ratio via Transform Panel.
- [x] Lock resize ratio when holding <kbd>CTRL</kbd> on shape creation.

### File format
- [x] Save simple file with version control in `.akira` format (No UI for alpha release).
- [x] Export Canvas and Artboards as PNG.
- ~Export Canvas and Artboards as SVG.~

### Options Panel
- [x] Control fill color.
- [x] Control border size and color.
- [x] Control border radius for Rectangle shapes.
- ~Control alignment relative to the Canvas or Artboard.~

### Layers Panel
- [x] Lock/Hide canvas items from layer panel.
- [x] Edit names of layers and artboards.
- [x] Delete layers and artboards.
- ~Search by name.~
- [x] Control shapes order via Layers panel.

### Extras
- [x] Shortcuts helper panel with <kbd>F1</kbd> key.

**Comment by mirekmazel** [comment]
@Alecaddd A note about the Super key – you might want to consider a different key combo, as Super is overriden in GNOME (and possibly other DEs as well). I know Akira is elementaryOS-focused, but it'd be nice if there weren't bigger usability issues in other DEs.

**Comment by albfan** [comment]
Typically <kbd>Ctrl</kbd>+<kbd>?</kbd> in GNOME. Maybe we can customize that as the shortcuts localized

**Comment by Alecaddd** [comment]
We could also consider using a function button, something like <kbd>F1</kbd> might make more sense.

**Comment by Alecaddd** [comment]
> Click and drag on an empty canvas area to select multiple shapes.

Moving the multiselection feature out of alpha as it needs a bit of rework of pretty much every section.
We'll tackle this as first actionable item for Alpha v2

**Comment by Alecaddd** [comment]
Alpha version released!
