### ISSUE TITLE
Canvas Issues

### ISSUE THREAD

**Issue by Alecaddd** [akiraux/Akira#217]
While I'm working on scrolling and dragging actions for the Canvas in order to enable standard movement and zooming like other apps, I noticed some issues with the canvas.

Here's everything I found out so far:
* Creating a shape not at 100% scale is visually broken. The shape is created in a separated location from the mouse click.
* ~~The rotation NOB doesn't keep the distance on zoom out.~~

*(The list might grow or shrink with time)*

Also the bounds of the canvas weren't updating properly and it wasn't possible to move items outside the edges of the initial size of the grid container. I fixed that so ignore it.

**Comment by albfan** [comment]
I see movement is constrained to an I visible limit. Lot to fix in scale tbh.

Should be some fix here and there. I can deal with it.

**Comment by Alecaddd** [comment]
I fixed the constraint issue, don't worry about that.
It's in my PR

**Comment by Alecaddd** [comment]
Another thing we should consider is splitting the Canvas.vala file into multiple smaller files handling unique aspects of the canvas library.

The Canvas.vala file is becoming larger and larger, causing merging issues, and making it hard to debug it and maintain it.

**Comment by albfan** [comment]
Totally agreed. Let's work on split it.

**Comment by Alecaddd** [comment]
Closing as this was fixed by #268
