### ISSUE TITLE
ESC activates Pointer button

### ISSUE THREAD

**Issue by Alecaddd** [akiraux/Akira#22]
No matter what button the user has currently active, hitting the escape key will revert the default selection to the Pointer

**Comment by isneezy** [comment]
Hi, I've tested tested this, and so far it is working as intended

**Comment by albfan** [comment]
@Alecaddd os this still valid?

**Comment by Alecaddd** [comment]
Yeah, this is not completely fixed yet as the ESC key should bring the docs back on the canvas no matter where the current focus is. Eg. Input fields, layers panel, color chooser, etc.
