### ISSUE TITLE
Build fails with Vala error (Creation method of abstract class cannot be public)

### ISSUE THREAD

**Issue by hazelnot** [akiraux/Akira#221]
## Expected Behavior
Being able to build Akira

## Current Behavior
Build fails with Vala error:

`../Akira/src/FileFormat/JsonObject.vala:34.5-34.33: error: Creation method of abstract class cannot be public.
    public JsonObject.from_object (Json.Object object) {
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../Akira/src/FileFormat/JsonObjectArray.vala:34.5-34.26: error: Creation method of abstract class cannot be public.
    public JsonObjectArray (Json.Object object, string property_name) {
    ^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 2 error(s), 0 warning(s)
[6/51] Generating com.github.akiraux.akira.appdata.xml_data_merge with a custom command.
ninja: build stopped: subcommand failed.`

## Your Environment (for bugs)

Arch Linux. Same error for manual building and trying to install via aur package.

**Comment by albfan** [comment]
See #157
