### ISSUE TITLE
Building on Nix

### ISSUE THREAD

**Issue by Ayplow** [akiraux/Akira#222]
## Expected Behavior

https://nixos.org/

> Nix is a powerful package manager for Linux and other Unix systems that makes package management reliable and reproducible. It provides atomic upgrades and rollbacks, side-by-side installation of multiple versions of a package, multi-user package management and easy setup of build environments.

Supporting nix allows users to build the application without having to circumvent its dependency system

## Current Behavior

No support, and no instructions for userland build.

## Possible Solution

Here is a derivation that builds the latest master. Used with nixos, it will perform a complete install as a desktop application

```nix
with import <nixpkgs> {};
stdenv.mkDerivation rec {
  pname = "Akira";
  version = "cab952dee4591b6bde34d670c1f853f5a3ff6b19";
  name = "${pname}-git-${version}";
  nativeBuildInputs = [
    meson pkgconfig cmake ninja python3

    wrapGAppsHook

    pantheon.vala gobject-introspection
  ];
  buildInputs = [
    pantheon.granite
    buildPackages.desktop-file-utils
    glib
    gtk3
    libgee
    libxml2
    gtksourceview
    json-glib
    goocanvas2
    libarchive
    cairo
  ];
  src = fetchFromGitHub {
    owner = "akiraux";
    repo = pname;
    rev = "${version}";
    sha256 = "1fp3a79hkh6xwwqqdrx4zqq2zhsm236c6fhhl5f2nmi108yxz04q";
  };
  
  setupHook = pkgs.writeText "setup.sh" ''
    MESON_INSTALL_PREFIX = $out;
  '';
  prePatch = "patchShebangs .";
}
```

## Context

Considering the current state of the project, this isn't really an issue - I was just sharing the derivation for people interested in testing it out and as a pointer when the project nears release.

**Comment by albfan** [comment]
You should add this as a PR so anyone can check it and build for that OS.

Copy/paste is just a step in the way.

**Comment by albfan** [comment]
As said, please share this as a PR someone can clone and execute, you can add instructions on a wiki or a README.
