### ISSUE TITLE
Transform panel issues

### ISSUE THREAD

**Issue by Alecaddd** [akiraux/Akira#223]
The transform panel works spectacularly, thank you so much for the great work @albfan.

Here's a list of a few tiny issues I stumbled upon.

- We should limit the number of decimals to 1, like I did in the opacity slider. Subpixels are not great for sharp design.
- The opacity slider doesn't update to the correct value when a shape is selected.
- It's impossible to generate shapes by click and dragging to the left on the canvas. Click and drag to the right works.

**Comment by albfan** [comment]
Thanks for the review. Let me check those things.

**Comment by Alecaddd** [comment]
Thanks for checking these.
Creating shapes doesn't work if you try to click and drag from bottom to top or from right to left, so there must be some issues with the transform panel locking the min value to 1.

**Comment by albfan** [comment]
Yes. It selects the bottom right nob by default. I think I can change to upper left in insert mode if height and width are too small, so we can create in both ways.

**Comment by albfan** [comment]
We need too a smarter input entries, they are little bit confusing right now on typing. Not so important right now.

**Comment by Alecaddd** [comment]
> We need too a smarter input entries, they are little bit confusing right now on typing. Not so important right now.

Yes, I find them a bit annoying too, but I guess we can iterate on them later on.

**Comment by Alecaddd** [comment]
All these issues have been fixed!
