### ISSUE TITLE
Removing custom vapis

### ISSUE THREAD

**Issue by albfan** [akiraux/Akira#243]
## Expected Behavior
Since version 0.43.90, vala provide updated vapis from goocanvas-2.0.

Would be great to remove our custom vapis and stick to upstream

Here I have vala 0.46

## Current Behavior
We maintain a custom vapi for goocanvas

## Possible Solution
remove custom vapis

## Context
flatpak still need this as the vala version still do not provides those vapis

@bilelmoussaoui I see io.elementary.App provides vala 0.40.

We need 0.43.90 to be able to remove custom vapis for goocanvas.

What's the roadmap for vala version in elementary SDK?

https://github.com/flathub/io.elementary.BaseApp

- Akira Version: master
- OS Info: arch linux

**Comment by bilelmoussaoui** [comment]
io.elementary.BaseApp follows what elementary ships I think. We can bump that if it's the case in elementary as well even if we shouldn't need that in a near future when elementary publish their sdk

**Comment by Alecaddd** [comment]
If I'm not wrong, elementary strictly sticks to the packages available in the current Ubuntu LTS.
I don't think they will upgrade the Vala package independently, but I could be wrong.
Pinging @danrabbit (sorry to bother you) to see if he can shed some light on it.

**Comment by bilelmoussaoui** [comment]
Just to be clearer, I don't plan to bump vala version on the elementary BaseApp on Flathub, it's too much work to update each app and ensure it builds correctly with a newer version.  Still, we can just not use the elementary base app and ship all our dependencies in the manifest we have here until there's an elementary SDK.

**Comment by danrabbit** [comment]
I think @tintou probably knows more about this than I do

**Comment by tintou** [comment]
elementary is using Ubuntu 18.04 + our [OS Patches PPA](https://launchpad.net/~elementary-os/+archive/ubuntu/os-patches/+packages?field.name_filter=&field.status_filter=published&field.series_filter=bionic) which is a layer in top of 18.04. This PPA contains an updated Vala to the latest Vala LTS as specified in the [Vala GNOME homepage](https://wiki.gnome.org/Projects/Vala) This means that the next Vala version we will get is 0.48.
You can probably use `meson.get_compiler('vala').version().version_compare('<=0.43.90')` to include its .vapi in the mean time
