### ISSUE TITLE
Rotation Snapping

### ISSUE THREAD

**Issue by danrabbit** [akiraux/Akira#249]
## Expected Behavior
Objects should snap to at least 90° increments when being rotated. This might require holding down a modifier like `Ctrl`

## Current Behavior
There doesn't appear to be any rotation snapping, even when holding down `Ctrl`

- Akira Version: undefined :upside_down_face: 
- OS Info: elementary OS Hera

**Comment by Alecaddd** [comment]
Yup, this was already implemented by @giacomoalbe in #227.
We put an hold on that PR because of the Canvas rewrite we've been doing.
