### ISSUE TITLE
Akira keeps opening on secondary display

### ISSUE THREAD

**Issue by KorbsStudio** [akiraux/Akira#258]
## Expected Behavior
Akira should open where I closed it last time

## Current Behavior
Akira opens on secondary screen by default every time

## Screenshots of the Problem
https://i.imgur.com/V9w0Ayc.gifv

## Environment
Linux korbs-HP-All-in-One-24-e014 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
NAME="elementary OS"
VERSION="5.1 Hera"
ID=elementary
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS 5.1 Hera"
VERSION_ID="5.1"
HOME_URL="https://elementary.io/"
SUPPORT_URL="https://elementary.io/support"
BUG_REPORT_URL="https://github.com/elementary/os/issues/new"
PRIVACY_POLICY_URL="https://elementary.io/privacy-policy"
VERSION_CODENAME=hera
UBUNTU_CODENAME=bionic

**Comment by Alecaddd** [comment]
Thanks for reporting this, I don't use a double monitor so I didn't stumble upon this before.
I'll try it out this week and see what's going on.

**Comment by albfan** [comment]
I have double monitor and  desktop remembers the last place where you left a window.

@KorbsStudio is this happening for other apps or only for Akira

**Comment by KorbsStudio** [comment]
Just Akira

**Comment by Alecaddd** [comment]
Ah, that's the issue I think, the maximized window state.
For me it doesn't reopen maximized, but in a somewhat full screen state. It might be related.

**Comment by KeizerDev** [comment]
I think it's related to the DE more then to the project. We should test it on other DEs as well to be sure. Also have a look at this https://askubuntu.com/questions/9921/dual-monitor-applications-opening-on-wrong-monitor

**Comment by isneezy** [comment]
I use 2 monitors setup at work and I've tested this on EOS Hera. It is strange coz I cant reproduce the issue. I'll send the screen record as soon I get into my laptop!

**Comment by KorbsStudio** [comment]
Recently updated the app today, issue is still occuring

**Comment by KorbsStudio** [comment]
I see this issue is still opened.
I'll look back into this tomorrow.

**Comment by albfan** [comment]
Try to move Akira not maximized to first display. Then maximize.

Close and reopen. Let us know how it goes (screencast if you want)

**Comment by KorbsStudio** [comment]
Seems to be working fine now, although I have upgraded to an ultrawide, and I usually only use my ultrawide only.
Anyway, it works:

[Video](https://i.imgur.com/jxyweJ5.mp4)
