### ISSUE TITLE
symbol lookup error:usr/lib/x86

### ISSUE THREAD

**Issue by DroWnThePoor** [akiraux/Akira#264]
- Akira Version: Akira-d74196b-x86_64.AppImage
- OS Info: Ubuntu 18.04 Gnome

./Akira-d74196b-x86_64.AppImage **Returns**
akira: symbol lookup error: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined symbol: hb_font_funcs_set_variation_glyph_func
**And then just ends**
I checked an verified that libpangoft2-1.0 is installed, and that symbolic is also present at the address.
It's confusing, because I downloaded this AppImage a month or so ago and I'm pretty sure I recall running it before.

**Comment by Alecaddd** [comment]
We didn't create the appimage and we're currently not supporting it.
I don't who built it or released it, and I'd recommend not using it.
We're working towards a first flatpak release.
