### ISSUE TITLE
Akira Crashes after selecting 2 objects

### ISSUE THREAD

**Issue by Micronetic** [akiraux/Akira#304]
## Current Behavior
When I try to select multiple "layers" in the sidebar the program crashes.
Can't edit the text.
Save and Save As doesn't work.

Here is a gif of what is happening: https://imgur.com/K3Xt7fs

- Akira Version:
akira-git r430.0b5ca73-1 from the AUR

- OS Info:
OS: Arch Linux 
     /  \        Kernel: 5.5.9-arch1-2 
    /\   \       Uptime: 57m 
   /      \      Packages: 996 (pacman) 
  /   ,,   \     DE: GNOME 3.36.0 
 /   |  |  -\    WM: Mutter 
/_-''    ''-_\   WM Theme: Materia-dark-compact 
                 Theme: Materia-dark-compact [GTK2/3] 
                 Icons: Tela-circle-grey-dark [GTK2/3] 
                 CPU: AMD Ryzen 5 2600 (12) @ 3.400GHz 
                 GPU: NVIDIA GeForce GTX 1660 
                 Memory: 2723MiB / 16012MiB

**Comment by Alecaddd** [comment]
Thanks for trying Akira.
As specified in the readme file, the software is still in early development, and we haven't released an alpha yet.
All these issues are know and we're working on it.
