### ISSUE TITLE
Building Akira on Solus

### ISSUE THREAD

**Issue by AUNaseef** [akiraux/Akira#312]
## Expected Behavior
I am following the instructions in the Readme to build Akira on Solus 4.1.
Since I already hunted down and installed all the dependencies and I am following the instructions properly, It should just compile fine.

## Current Behavior
The build fails with an error related to Granite.

## Possible Solution
I don't know if this is a problem specific to Solus, I remember having the same problem on elementary. Maybe there are errors in the code that has to be fixed. Could I be using versions of libs that are incompatible with Akira?

## Steps to Reproduce (for bugs)
1. Follow the build instructions on Solus

## Context
```
../src/Layouts/HeaderBar.vala:459.25-459.42: error: The name `AccelLabel' does not exist in the context of `Granite'
        var label = new Granite.AccelLabel.from_action_name (text, accels);
                        ^^^^^^^^^^^^^^^^^^
../src/Layouts/HeaderBar.vala:464.13-464.17: error: The name `label' does not exist in the context of `Akira.Layouts.HeaderBar.create_model_button'
            label.attach_next_to (
            ^^^^^
../src/Layouts/HeaderBar.vala:471.21-471.25: error: The name `label' does not exist in the context of `Akira.Layouts.HeaderBar.create_model_button'
        button.add (label);
                    ^^^^^
Compilation failed: 3 error(s), 0 warning(s)
ninja: build stopped: subcommand failed.
```
## Your Environment (for bugs)
- Akira Version: Git/master
- OS Info: Solus 4.1 Fortitude - Budgie Edition

**Comment by bilelmoussaoui** [comment]
Granite version shipped in solus is too old.

**Comment by AUNaseef** [comment]
@bilelmoussaoui the version I have installed right now is 5.2.5-16, Which is higher than what's written in the readme. I'll see if I could install a newer version, maybe from unstable repos. Thanks!

**Comment by bilelmoussaoui** [comment]
The readme needs to be updated then. We should also bump the required version in the meson.build file too

**Comment by Alecaddd** [comment]
We're using granite 5.3.0, I updated the readme and dependency version.
We don't have access to the aur for granite so you should ask to the maintainer of that package to update the version, or compile and install granite locally.
