### ISSUE TITLE
Deleting an image crashes the app

### ISSUE THREAD

**Issue by Hedronmx** [akiraux/Akira#317]
## Expected Behavior
Pressing the Delete key when an image should just delete the image

## Current Behavior
Pressing the Delete key when an image is selected crashes the app to a Segmentation fault

## Possible Solution
No idea... :(

## Steps to Reproduce (for bugs)
1. Open an image
2. Select it
3. Press delete key
4. cry

## Context
Well I cant delete images because it crashes the app, so any bad images I have imported are now forever in the app .

## Screenshots of the Problem

https://gfycat.com/forsakenadoredhusky

## Your Environment (for bugs)
```
Linux carlos-pc 5.3.0-45-generic #37~18.04.1-Ubuntu SMP Fri Mar 27 15:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
NAME="elementary OS"
VERSION="5.1.2 Hera"
ID=elementary
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS 5.1.2 Hera"
LOGO=distributor-logo
VERSION_ID="5.1.2"
HOME_URL="https://elementary.io/"
SUPPORT_URL="https://elementary.io/support"
BUG_REPORT_URL="https://github.com/elementary/os/issues/new"
PRIVACY_POLICY_URL="https://elementary.io/privacy-policy"
VERSION_CODENAME=hera
UBUNTU_CODENAME=bionic
```

- Akira Version: Not sure how to check version of Akira but I just git pulled this april 2nd
- OS Info: elementary OS 5.1.2 Hera

**Comment by Alecaddd** [comment]
That's a known issue due to the restructuring we did on artboards and layers.
Will most likely be fixed by #309

**Comment by Hedronmx** [comment]
I see! Sorry if this issue is not needed

**Comment by Alecaddd** [comment]
Eheh, no apologies needed, every bug report is an important bug report that helps us to keep track of everything.
Thank you so much 😄
