### ISSUE TITLE
Create a fancy but scary warning dialog for the Alpha release

### ISSUE THREAD

**Issue by Alecaddd** [akiraux/Akira#329]
The alpha release is upon us, which means probably many users will see this app popping out in their app stores, and upon using it the first will most likely wonder why so many basic features are missing.

We should implement a warning dialog that triggers automatically when the app is opened the first time and warns the user that this is an alpha and if you use it too much a black hole might open i your bathroom...or something like that.

Nonetheless, if should be a nice and stylish dialog, with quick links to the repo, donations, and issue tracker.

**Comment by albfan** [comment]
It can be reused as a news dialog that you can see each time app is updated, with typical "Don't show again", and a check on preferences "Show news dialog on startup"

**Comment by Alecaddd** [comment]
Indeed, later on we can use it to list the changes in a new version.
