### ISSUE TITLE
Change shape size move the shape

### ISSUE THREAD

**Issue by QuentinLeloire** [akiraux/Akira#335]
Hi, I found a bug when I tested the app :

## Expected Behavior
Shapes don't need to change (x, y) position

## Current Behavior
Shapes moving to bottom direction

## Possible Solution
Possibly an error with 0 with/height ?

## Steps to Reproduce (for bugs)
1. Start app
2. Insert Artboard
3. Insert Shape
4. change shape size with corner and make them smallest as possible.
5. Shape position as changed

## Context
I tried to change size of shape with mouse   

## Screenshots of the Problem
here shape insert :

![image](https://user-images.githubusercontent.com/22280157/79901950-f4d27d80-8410-11ea-9b8f-04c90ddf148f.png)

after changing shape size :

![image](https://user-images.githubusercontent.com/22280157/79902087-2a776680-8411-11ea-9bf1-c7dbe3ea3904.png)

## Your Environment (for bugs)
```sh
Linux quentin-pc 5.4.31-1-MANJARO #1 SMP PREEMPT Wed Apr 8 10:25:32 UTC 2020 x86_64 GNU/Linux
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.manjaro.org/"
SUPPORT_URL="https://www.manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux

Running with KDE
```

- Akira Version: 0.1 (master branch)

**Comment by Alecaddd** [comment]
Hi, thanks for using Akira and for detailed bug report.
We're aware of this issue, which it was introduced after the Artboard implementation, and we're already working on it in PR #322
