### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by lrmodesgh** [akiraux/Akira#339]
i have always only used inkscape and create commons resources so far in my ui/ux work flow and my most favourable os is GNU/Linux os, with elementary flavour. 

And akira so far, i am trying to integrate into my workflow. Really glad to know that the community is dedicated to turn this out into a practically usable project for life.

------------------

**My request** is, to have a resource/asset management for building ui elements, components, organs and organisms.

for instance, the nounproject :  https://thenounproject.com/apps/   provides app to all other operating systems other than gnu/linux.  

for all these years using my account in the nounproject, i have used several hundred of icons and have contributed a few. My workflow mainly comprises of paper pencil, scan, inkscape, gimp and then css for most part. 

however all these are manual. For every project there is a character that is transformed or manifested into a design language. For instance, u may well know how elementary human interface design guidelines have balanced between diversity and uniformity to create a gradual ux change among new coming gnu/linux users.

Thus i believe, akira will be in future can handle in aiding/managing design language systems and generate design kits that are functional.

i really like to contribute in some way. I am learning vala after long gap again, lot of changes and updates. coooool.

**Comment by albfan** [comment]
We got you basically covered on #63, feel free to add comments there.

We love the idea, but still not at this stage.
