### ISSUE TITLE
Pressing Ctrl when scaling an image should not change its original aspect ratio to 1:1

### ISSUE THREAD

**Issue by ashraf2033** [akiraux/Akira#341]
## Expected Behavior
Pressing Ctrl while scaling images should reserve original aspect ratio of scaled image

## Current Behavior
 Pressing Ctrl button while scaling an image after importing it directly causes image's aspect ratio to be 1:1 

## Steps to Reproduce (for bugs)
1.Launch Akira
2.Import an image that isn't a square
3.scale while holding Ctrl button

## Context
It's a habit of mine to hold control to reserve aspect ratio of any object I scale

## Screenshots of the Problem
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13683750/80844948-9bd4c780-8c10-11ea-84ab-c57b60d27a82.gif)

- Akira Version: v0.0.1 - alpha
- OS Info: Manjaro 20

**Comment by Alecaddd** [comment]
Thanks for the report, I know what's the problem and I'll fix it this weekend.
Just so you know, images imported in Akira have their aspect ratio locked already, so you don't need to hold CTRL to scale them, as you can see from the pressed lock icon in the transform panel.

**Comment by isneezy** [comment]
@Alecaddd I can also confirm this problem and I can also see that the aspect ratio is locked. The other issue I found besides this that pressing shift or Ctrl while drawing any shape/artboard doesn't keep the aspect of 1:1
