### ISSUE TITLE
ArtBoards shouldn't have flip options 

### ISSUE THREAD

**Issue by ashraf2033** [akiraux/Akira#342]
## Expected Behavior
Flip options should be disabled for ArtBoards

## Current Behavior
User can flip ArtBoards vertically and horizontally 

## Steps to Reproduce (for bugs)

1.Launch Akira
2.Create an ArtBoard
3.Click on flip buttons

## Screenshots of the Problem
![Artboards flip](https://user-images.githubusercontent.com/13683750/80923422-5dfcae00-8d8c-11ea-8a43-86ccda4a8119.gif)

- Akira Version: 0.0.1
- OS Info: Manjaro 20

**Comment by Alecaddd** [comment]
Indeed
