### ISSUE TITLE
Inserting shapes in artboards repeatdly causes black areas on some icons and hiding current layers

### ISSUE THREAD

**Issue by ashraf2033** [akiraux/Akira#345]
## Expected Behavior
Inserting shapes in artboards repeatedly  without problems

## Current Behavior
Inserting shapes in artboards repeatedly causes  black areas on layout  icons and layers to be hidden

## Steps to Reproduce (for bugs)
1.Launch Akira
2.Insert Artboard
3.Insert two shapes in the Artboard repeatedly with the help of shortcuts

## Context
This might seem as an edge case, but for a design app I believe this is a valid case.

## Screenshots of the Problem
![INsertingshapesrep](https://user-images.githubusercontent.com/13683750/81208973-88db4200-8fd8-11ea-9179-bda290cd74ea.gif)

## Your Environment (for bugs)
Termnal kept printing this line :
```
Linux quality-soul 5.6.8-1-MANJARO #1 SMP PREEMPT Wed Apr 29 19:05:17 UTC 2020 x86_64 GNU/Linux
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.manjaro.org/"
SUPPORT_URL="https://www.manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
```
- Akira Version: 0.0.1
- OS Info: Manjaro 20

**Comment by Alecaddd** [comment]
I'm investigating this and I think I got on the right track.
It seems that our paint method for the artboard is getting called all the time, literally every millisecond non stop if there's at least 1 item inside an artboard.
https://github.com/akiraux/Akira/blob/697c97774184a90714abe0f54fbc3e4c432e99be/src/Lib/Models/CanvasArtboard.vala#L206

This method also triggers the redraw of the canvas, which might be the culprit for all those visual glitches.

**Comment by Alecaddd** [comment]
@ashraf2033 would you be able to comment out the `canvas.queue_draw ();` method, and see if those issues remain?

**Comment by ashraf2033** [comment]
For some reason I can't reproduce this bug anymore, I'm also facing problem with uninstalling Akira development and can't update it, but I'm not having any problem with uninstalling Akira default, don't know what I'm missing

**Comment by Alecaddd** [comment]
Uh, let me check, maybe we forgot the uninstall recipe for the dev version.

**Comment by Alecaddd** [comment]
Closing this as it can't be reproduced
