### ISSUE TITLE
Huge black border around window

### ISSUE THREAD

**Issue by SkyyySi** [akiraux/Akira#348]
So I just installed Akira, and imediatly had a big issue: due to the elementary theme, my window manager (i3-gaps with picom and the Nordic GTK theme) draws a very, very large black border around the window. I also had this issue when setting the eos theme as my system theme, in which case all GTK apps suffered from this issue. It also happened when using GNOME - the only place it works correctly is Pantheon. Could you please investigate this issue?
PS: I use Arch BTW

**Comment by ashraf2033** [comment]
@SkyyySi I use Manjaro Gnome and akira works fine, but I remember installing Elementary theme

**Comment by Alecaddd** [comment]
Did you install Akira via the official Snap?
We don't directly support all the distributions and DEs as we don't have the resources right now.
If the elementary OS stylesheet causes this issue in other apps other than Akira, than it's not an Akira issue.
