### ISSUE TITLE
Will there be AppImage, .DEB, .RMP, PPA releases ?

### ISSUE THREAD

**Issue by Qik000** [akiraux/Akira#349]
Will Akira feature Deb, Rpm and AppImage formats or debian/ubuntu PPA`s ? Snap and Flat are very slow, and create clutter, 1 package manager is enough.

**Comment by Alecaddd** [comment]
We're open to contributors and supporters to ship Akira in other managers.
We currently only have the resources to ship it via the elementary OS AppCenter, via Snap, and Flatpak.
