### ISSUE TITLE
How to snap items to Artboard edges?

### ISSUE THREAD

**Issue by nataneb32** [akiraux/Akira#352]
I am currently looking to contribute. So i am trying to understand where is the moving/grab of canvas items handle. I'm guessing it is inside the eventbus, but not sure how it works.

Ps: I'm trying to make the canvas items snap to the artboard :smiley:

**Comment by albfan** [comment]
@nataneb32 is more actionable to open an issue about your goal and look for hints on how to solve it.

Subject "canvas items snap to the artboard"

A little description on your goal and we can provide hints about it

Do some research about how magnetic alghorithms work will help here too like https://en.wikipedia.org/wiki/Nearest_neighbor_search

**Comment by nataneb32** [comment]
okay. thank you.

**Comment by Alecaddd** [comment]
This is also a good starting point to force us to write better comments and improve the documentation of our code base.

As a quick overview, the `EventBus` is only used as the unique source where all the events get emitted. Each file listen to those events and then handle them accordingly. No actual function is written in the EventBus.

In this case, all the click actions and interactions with the `Canvas` are handled in the `Lib/Canvas.vala` file, specifically here: https://github.com/akiraux/Akira/blob/78cc1ec9513e26522168d238accc736009f370f8/src/Lib/Canvas.vala#L188

You can see we're handling different `MODES` with a switch/case method, and the one you're looking for is the `MODE_PAN` right here: https://github.com/akiraux/Akira/blob/78cc1ec9513e26522168d238accc736009f370f8/src/Lib/Canvas.vala#L251

**Comment by isneezy** [comment]
I think #425 may solve this issue. @nataneb32 test it and give your feedback

**Comment by Alecaddd** [comment]
This feature was implemented in #509
