### ISSUE TITLE
The splash screen won't disappear

### ISSUE THREAD

**Issue by piiskop** [akiraux/Akira#357]
## Expected Behavior

The splash screen disappears.
## Current Behavior

The splash screen won't disappear and there's no button nor anything else to remove it and start sketching.
## Possible Solution

Remove the splash screen!
## Steps to Reproduce (for bugs)

1. Open the application.
2.
3.
4.

## Context

I was opening the app for the first time.
## Your Environment (for bugs)

"Cinnamon with software rendering"
Linux peacecop-GL752VW 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

- Akira Version: v0.0.1
- OS Info: "Ubuntu 20.04"

**Comment by Alecaddd** [comment]
Did you build Akira from source or installed from somewhere else?
Can you provide a screenshot of the splash screen?

It should also disappear after first run

**Comment by piiskop** [comment]
I did install it using /sudo snap install --edge akira/.

Using /ESC/, the splash screen disappears. How in our holy green world 
does one figure out this intuitively? Why do you we need that splash 
screen anyway?

I was just curious about FOSS on painting because /krita/ doesn't work 
well on /Ubuntu 20.04 /and /Cinnamon (with software rendering)/. And 
/akira/ doesn't suit at all because the pen ability is greyed out, 
probably not implemented yet.

*peacecop kalmer:*

*Instituudi tee 3-27 *

*76902 * *Harku *

*Harku*

*Harjumaa*
Estonia

*+372 652 4228 *

*+372  5620 4556 *

*__________________________________________________________________ *

**Comment by Alecaddd** [comment]
The splash screen is there for the purpose of telling users that Akira is an alpha version not yet released to the public and a lot of things don't work.
A missing closing button is obviously a bug, we didn't do it on purpose, and we don't expect the user to intuitively press ESC.

Also, Akira is not for painting.
I'd suggest to not install applications before reading what they actually do.

**Comment by piiskop** [comment]
What's the purpose of /Akira/ then? We have /Inkscape/ already and we 
also have /Draw.io/ or it has a newer name now. What does /Akira/ have 
so special that others don't or rather what will /Akira/ have as it's on 
alpha-stage? And why do you have to inform anybody about its 
alpha-state? alpha-state is only for developers and developers of 
/Akira/ know that, I suppose. Others shouldn't be able to get it at all 
before it gets past alpha... if it will get past alpha. Once the 
software is ready, put it available, now it's just confusing as you make 
advertisements for it and it isn't even ready - what a disappointment! 
Do you want your potential users escape it as we have to escape the 
splash screen? And yes, I read that it's meant for UX design. So my 
question remains as this is nothing special unless it will have 
something special.

*peacecop kalmer:*

*Instituudi tee 3-27 *

*76902 * *Harku *

*Harku*

*Harjumaa*
Estonia

*+372 652 4228 *

*+372  5620 4556 *

*__________________________________________________________________ *

**Comment by abienz** [comment]
From the readme:

"Akira is a native Linux Design application built in Vala and GTK. Akira focuses on offering a modern and fast approach to UI and UX Design, mainly targeting web designers and graphic designers. The main goal is to offer a valid and professional solution for designers who want to use Linux as their main OS."

The Snap wasn't created by the Akira team it was produced by a 3rd party dev who wanted to help out with the project

Inkscape is a tool designed for vector illustration and print design, Akira has been built from the ground up to be a web/mobile design tool, they serve different purposes.

**Comment by LucileDT** [comment]
As someone wanting to draw mockups since ages under Linux, I find Akira very useful: it's the only open source specific app doing that for now. Because that's the purpose of Akira: making mockups.
