### ISSUE TITLE
goocanvad not found

### ISSUE THREAD

**Issue by JVariance** [akiraux/Akira#359]
I try to build Akira UX.
But I get the error 'Dependency "goocanvas-2.0" not found, tried pkgconfig and cmake'.
How can I resolve it?

I already have installed 'gir1.2-goocanvas-2.0:i386' and 'gir1.2-goocanvas-2.0'.

**Comment by Alecaddd** [comment]
You need to install `libgoocanvas-2.0-dev`, or if you use Gnome builder, load the repo and build it from within so the builder takes care of all the dependencies.
