### ISSUE TITLE
Dependency Issue

### ISSUE THREAD

**Issue by nishp77** [akiraux/Akira#368]
## Expected Behavior
The build for the application should be done
## Current Behavior
![image](https://user-images.githubusercontent.com/35785259/87481008-1a2bed80-c5f4-11ea-95d8-fa26215c9fb5.png)

## Possible Solution
The dependency I installed was:-

![image](https://user-images.githubusercontent.com/35785259/87481079-3c257000-c5f4-11ea-9fac-83086d529718.png)

I need help if any has solved this issue as I wasn't able to find the exact dependency so would just like to ask you that why the above dependency won't work? 

- OS Info: Pop OS

**Comment by Alecaddd** [comment]
You need to install the libjson-glib-dev version if you want to compile akira from source.

**Comment by rubbieKelvin** [comment]
please how do i install the dependencies on fedora 32?🥺🥺🥺

**Comment by albfan** [comment]
@rubbieKelvin dnf install <whatever>-devel but see that is offtopic here.
