### ISSUE TITLE
ZipArchiveHandler : no expression allowed between array brackets

### ISSUE THREAD

**Issue by BZHDeveloper** [akiraux/Akira#378]
https://github.com/akiraux/Akira/blob/master/src/FileFormat/ZipArchiveHandler.vala#L351

With latest version of vala compiler, create array without expression inside brackets

```
uint8[] buffer = new uint8[64];

**Comment by Alecaddd** [comment]
We're based on Ubuntu 18.04, so we don't have the latest Vala release.
We will update when necessary.
