### ISSUE TITLE
Please don't change tags!

### ISSUE THREAD

**Issue by alerque** [akiraux/Akira#386]
Tagging an Alpha release was great! But good release practice starts now. Deleting the tag and re-creating it (or rather deleting it and creating a similar one) was the wrong thing to do, that creates all sorts of messes downstream from broken packaging to git of forks that have tags that don't exist upstream. Just bump the patch release number if necessary and don't stress over it. But the mess made by retroactively tryng to change a tag is worse than just having two releases in quick succession.

**Comment by Alecaddd** [comment]
Yeah, sorry.
I was just experimenting and I assumed it would have been okay since it's the first one.
I won't do that anymore :sweat_smile:

**Comment by alerque** [comment]
....and now you have an Alpha release tag that is newer than the release tag of the same semver. So a tag that sorts as older in almost every revision parsing system out there is actually newer.

**Comment by alerque** [comment]
...and now you just skipped 10 versions! I understand the desire to crank it up to 11, but why did you skip v0.0.2, v0.0.3, v0.0.4, v0.0.5, v0.0.6, v0.0.7, v0.0.8, v0.0.8, v0.0.9, and v0.0.10?

https://semver.org/

**Comment by albfan** [comment]
@Alecaddd we can go with v0.0.1-alpha2, ... whatever. 

We really want to go for 1.0.0 at some point, so all this doesn't really matter.

**Comment by Alecaddd** [comment]
I was having troubles with the elementary OS release bot.
My bad for the 11 variation, I'll continue with 12, 13, 15, etc for the alpha cycle, aiming for 0.1.0 as Beta.

**Comment by alerque** [comment]
Thanks for continuing with `v0.0.12`! That's better than `v0.0.1-alpha2` because it sorts correctly as newer than other released tags. Using the zero-dot-zero-dot-N for Aplhas is fine, you can keep counting up in that space as long as you need to.

**Comment by FabioLolix** [comment]
as an AUR packager with a lot of pkgbuilds at hand (150+) I don't care about how many versions do you skip but do it in a consistent manner
