### ISSUE TITLE
Avoid potential crash inside set_accels_for_action()

### ISSUE THREAD

**Issue by danfe** [akiraux/Akira#392]
Something fishy is going on inside `set_accels_for_action()` when its second argument is passed from the `Gee.MultiMap<string, string>`: apparently the `string[] accels` gets garbled somehow so the program crashes inside the `strlen()` call shortly after.  I've observed this on FreeBSD, and it happens regardless of the compiler being used (Clang 10.0.1 or GCC 7.5.0).

Changing the second argument to `{ typing_accelerators[action].to_array ()[0] }` gets rid of the crash.  Another option would be to switch to map iterator, which also is a little more efficient and easy on eyes, e.g.:
```vala
  var iter = action_accelerators.map_iterator ();
  while (iter.next ()) {
     app.set_accels_for_action (ACTION_PREFIX + iter.get_key (), { iter.get_value () });
  }
```
See also: https://github.com/Alecaddd/sequeler/issues/96

**Comment by albfan** [comment]
Hi, danfe, I suppose you're building Akira under Mac right? Please use this issue to describe how to reach a problem and then you can open one or more PR with possible solutions.

I'm aware clang is more strict about building and executing, and maybe we can workaround it somehow, but first we need a way to reproduce it.

**Comment by danfe** [comment]
> I suppose you're building Akira under Mac right?

As I've said, I'm using FreeBSD.

> I'm aware clang is more strict about building and executing

As I've said, the problem does not go away if I build Akira with GCC.  It might, however, still be a Clang issue since I didn't rebuild the entire Vala/GTK stack with GCC, I'll try that for completeness' sake today, which makes sense as the bug might not be in the Akira [after all](https://gitlab.gnome.org/GNOME/vala/-/issues/626).

> and maybe we can workaround it somehow, but first we need a way to reproduce it.

Well, just build, then run the program, and it would crash immediately with segmentation fault before it has a chance to draw anything on the screen.

**Comment by Alecaddd** [comment]
Hey @danfe, I create the PR #396 with your helpful suggestion, would you be able to check if that solves the problem?

**Comment by danfe** [comment]
> would you be able to check if that solves the problem?

Yes, it does solve the problem (which is unsuprising since I've tested this approach earlier), thanks!
