### ISSUE TITLE
Large black border on i3

### ISSUE THREAD

**Issue by dannycolin** [akiraux/Akira#395]
## Expected Behavior

Akira shouldn't have a huge black border around the main window

## Current Behavior

Akira has a large black border around the main window. This is probably due to the client-side decoration (CSD) shadow applied by GTK.

## Possible Solution

The user could use a hackaround by adding `.window-frame {box-shadow: none; margin: 0}` in `~/.config/gtk-3.0/gtk.css`. However, this isn't an ideal solution since not everyone is familiar with gtk configuration file or even know it exists.

Another solution would be to apply a different css file from the application based on the WM of the user.

## Steps to Reproduce (for bugs)

1. Use only i3 as your WM
2. Start AkiraUX

## Context

It makes the main window very small and limits the ergonomic of the application 

## Screenshots of the Problem
 

![image](https://user-images.githubusercontent.com/7339076/89841034-e9ca6700-db3f-11ea-8b03-4717c3180acd.png)

## Your Environment (for bugs)

- Akira Version: v0.0.1-alpha
- OS Info: Fedora 32 Linux Earth 5.7.11-200.fc32.x86_64
- WM: i3

**Comment by albfan** [comment]
Can you attach an image with the css tweaked?

the mentioned window manager is https://i3wm.org/

**Comment by dannycolin** [comment]
> Can you attach an image with the css tweaked?

I haven't found a way to apply it to the flatpak version. I mentioned this solution only because it's a known hackaround for this issue.

I investigated a bit more and found out that forcing the application to use the Adwaita theme also resolve the issue. I used the following command: `flatpak run --env=GTK_THEME=Adwaita com.github.akiraux.akira`.

Is there any reason why Akira force the Elementary theme?

**Comment by Alecaddd** [comment]
I had the same problem with Filezilla installed via flatpak.
I'll check how I solved it.

We force the elementary theme because Akira is mostly based on the elementary HIG, and it help us maintain the visual consistency across distros, and removes the overhead of not knowing which icons or windows style the user will see in his DE.

Thanks for the report.

**Comment by bilelmoussaoui** [comment]
I think this issue is caused by the elementary stylesheet, see https://github.com/elementary/stylesheet/issues/468

**Comment by gfarrell** [comment]
I've installed Akira via the AUR (using `yay`) and I have the same problem on Arch using i3 (well, i3-gaps). This is what it looks like:

![screenshot_2020-10-04_202351](https://user-images.githubusercontent.com/314331/95025158-c58e9080-067f-11eb-9b29-786bbde597c2.png)

The gtk.css tweak suggested above does not work for me.

**Comment by albfan** [comment]
This is a problem with i3wm and elementary theme (fixed theme for Akira). It's unlikely we will fix it here. 

https://github.com/alainm23/planner/issues/303#issuecomment-613968198

This patch base the solution on detect elementary OS. As we fix the elementary theme we could solve it the same way:

https://github.com/NixOS/nixpkgs/commit/2c74cdac47e17fff9c0b0e7554bbcbdf319cbcdd

but is not akira duty to fix the world, but report upstream what is not working. (i3wm+elementary)

We can reopen if elementary refuses the isssue.

**Comment by albfan** [comment]
FTR:

Just tried, i3-wm and i3-gaps and workaround :-1: 
`~/.config/gtk-3.0/gtk.css`
```
window decoration {
    box-shadow: none;
    margin: 1px;
}
```

works  any single time:

Without:
![Captura de pantalla de 2020-10-05 16-36-49](https://user-images.githubusercontent.com/220968/95093985-acdab500-0729-11eb-86f5-ecd5fd0f3d6a.png)

With:
![Captura de pantalla de 2020-10-05 16-31-27](https://user-images.githubusercontent.com/220968/95093986-ad734b80-0729-11eb-9576-f09ed5651c3b.png)

The only way I can see this failing is that if you already has an open instance of akira it reuses the config, so be sure to close any existing akira instance before apply the workaround.
