### ISSUE TITLE
Bug: App doesn't launch

### ISSUE THREAD

**Issue by jtrees** [akiraux/Akira#398]
## Expected Behavior
The app should open.

## Current Behavior
Attempting to start the app does nothing.

## Steps to Reproduce (for bugs)
1. Install Akira
2. Try to open it

## Context
Starting the app via a terminal yields this error:

```
Settings schema 'com.github.akiraux.akira' does not contain a key named 'recently-opened'
```

I also got the following when installing via apt:

```
No such key 'button-layout' in schema 'org.gnome.mutter:Pantheon' as specified in override file '/usr/share/glib-2.0/schemas/20_elementary.pantheon.wm.gschema.override'; ignoring override for this key.
No such key 'enable-animations' in schema 'org.gnome.mutter:Pantheon' as specified in override file '/usr/share/glib-2.0/schemas/20_elementary.pantheon.wm.gschema.override'; ignoring override for this key.
```

## Your Environment (for bugs)
- Akira Version: 0.0.11
- OS Info: elementary OS 5.1.7 Hera
- Kernel: Linux 5.4.0-42-generic

**Comment by Alecaddd** [comment]
> I also got the following when installing via apt:

How did you install it via apt if we didn't release an apt package for it?
If you're on elementary you should install it via the AppCenter

**Comment by jtrees** [comment]
Er... good question. First I installed via AppCenter but since it didn't work, I removed it and then tried via the terminal, like so:

```
sudo apt install com.github.akiraux.akira
```

**Comment by Alecaddd** [comment]
Ah, doing that will install the version coming from the appcenter, as it's the same source.
Based on your error it seems that the `recently-opened` gsetting wasn't properly installed during the installation process.
That's very strange.

Is your version of elementary tweaked or modified in any way?

**Comment by jtrees** [comment]
It's not a fresh install. I've been using this base since Hera came out, changing settings, installing software, etc.. But I don't remember doing anything particularly funky, like messing with gsettings, using custom themes or the like.

**Comment by jtrees** [comment]
I do remember trying out the pre-alpha of Akira from git though. Before installing the AppCenter version, I did a `ninja uninstall` but perhaps it didn't clean up everything?

**Comment by Alecaddd** [comment]
> I do remember trying out the pre-alpha of Akira from git though. Before installing the AppCenter version, I did a `ninja uninstall` but perhaps it didn't clean up everything?

That might be it, but the uninstall should have removed the old schema.
I guess you could download the updated repo and do a `ninja install` to get the updated schema.

**Comment by albfan** [comment]
remember to clean all akira on `/usr/local` and use `meson --prefix=/usr` to install everything in right place (i18n will not work properly for example on `/usr/local`

Let us know if that fixes it. Missing entries from schema (`'recently-opened'`) seems to be related with an old installation

**Comment by jtrees** [comment]
No luck.

I had already cleaned my Akira install from `/usr/local`. Searching for `akira` in the `/usr/local` directory confirms that the files have been removed.

Checking out version 0.0.12 from git and installing it with ninja (with `/usr` as the prefix) also results in the following messages:

```
Compiling gsettings schemas...
No such key 'button-layout' in schema 'org.gnome.mutter:Pantheon' as specified in override file '/usr/share/glib-2.0/schemas/20_elementary.pantheon.wm.gschema.override'; ignoring override for this key.
No such key 'enable-animations' in schema 'org.gnome.mutter:Pantheon' as specified in override file '/usr/share/glib-2.0/schemas/20_elementary.pantheon.wm.gschema.override'; ignoring override for this key.
```

Running the app afterwards still fails and yields...

```
(Akira:23037): GLib-GIO-ERROR **: 14:37:07.435: Settings schema 'com.github.akiraux.akira' does not contain a key named 'recently-opened'
[1]    23037 trace trap  com.github.akiraux.akira
```

**Comment by albfan** [comment]
Looking around for those errors. I see 20_elementary.pantheon.wm.gschema.override in a package called gala

The Pantheon Window Manager

I see those errors installing anything so I think you should report that to gala package.

Then if you cannot compile glib schema it is normal that you cannot run correctly any app using gsettings.

As test you can uninstall those faulty overrides and surely all will work as expected.

Closing this error as it is not related with akira really (please provide more info to reopen it). You can always use flatpak to test it (in an isolate sandbox)

**Comment by albfan** [comment]
I checked again, and those are only warnings. schemas are compiled correctly.

So my test was:

commit 6c4ba02 introduce recently-opened key.

- build and install 6c4ba02^ (parent commit)
- check 6c4ba02 and only build.
- manually copy build/src/com.github.akiraux.akira to /usr/bin (a binary that use recently-opened)

As expected I can see the error:

```
$ com.github.akiraux.akira 

(Akira:49486): GLib-GIO-ERROR **: 23:17:44.685: Settings schema 'com.github.akiraux.akira' does not contain a key named 'recently-opened'
`trap' para punto de parada/seguimiento (`core' generado)
```

that means the gschemas.compiled you have miss that key.

In that situation, my dconf GUI shows:

![Captura de pantalla de 2020-08-15 23-21-04](https://user-images.githubusercontent.com/220968/90321868-1b7f6b80-df4e-11ea-9bce-c97d24a0206b.png)

Two key values that do not belong to any schema (version and recently-opened)

on a correct installation you should have a xml describing that key:

```
/usr/share/glib-2.0/schemas/com.github.akiraux.akira.gschema.xml
86:        <key name="recently-opened" type="as">
```

so 

```
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
```

should include that and allow you to use that key.

To check what compiled schemas you are using you can check:

```
$ strace -f gsettings list-recursively com.github.akiraux.akira |& grep gschemas | grep -v ENOENT
openat(AT_FDCWD, "/usr/share/glib-2.0/schemas/gschemas.compiled", O_RDONLY) = 3
```
here I see the gschemas.compiled my gsettings is reading and that show me (for a recent install:

```
$ gsettings list-recursively com.github.akiraux.akira
com.github.akiraux.akira border-size 1
com.github.akiraux.akira recently-opened @as []
com.github.akiraux.akira right-paned 813
com.github.akiraux.akira use-symbolic false
com.github.akiraux.akira export-folder ''
com.github.akiraux.akira open-quick false
com.github.akiraux.akira export-scale 1
com.github.akiraux.akira window-height 714
com.github.akiraux.akira window-width 1366
com.github.akiraux.akira export-compression 0
com.github.akiraux.akira border-color '#AAAAAA'
com.github.akiraux.akira fill-color '#CCCCCC'
com.github.akiraux.akira pos-x 0
com.github.akiraux.akira export-alpha true
com.github.akiraux.akira export-paned 300
com.github.akiraux.akira export-height 600
com.github.akiraux.akira show-label true
com.github.akiraux.akira set-border true
com.github.akiraux.akira left-paned 331
com.github.akiraux.akira export-quality 100
com.github.akiraux.akira export-format 'png'
com.github.akiraux.akira export-width 1000
com.github.akiraux.akira dark-theme false
com.github.akiraux.akira pos-y 0
```

Look around where you have an old com.github.akiraux.akira.gschema.xml that is missing that key

**Comment by jtrees** [comment]
Wow! Thanks so much for the detailed information here, @albfan. I was able to resolve the issue thanks to your instructions!

The steps I took went like this:

```sh
$ strace -f gsettings list-recursively com.github.akiraux.akira |& grep gschemas | grep -v ENOENT
openat(AT_FDCWD, "/usr/share/glib-2.0/schemas/gschemas.compiled", O_RDONLY) = 3
openat(AT_FDCWD, "/usr/local/share/glib-2.0/schemas/gschemas.compiled", O_RDONLY) = 3
# Ah look, there are schemas under /usr/local

$ ls /usr/local/share/glib-2.0/schemas
gschemas.compiled
# Sure enough. Only the compiled schemas remain though.

# Let's see what we can do about it.
$ sudo glib-compile-schemas /usr/local/share/glib-2.0/schemas/
No schema files found: removed existing output file.

$ ls /usr/local/share/glib-2.0/schemas
# Nothing.
```

After this, launching Akira works!

**Comment by albfan** [comment]
cool!
