### ISSUE TITLE
Fix gtk_main_quit: assertion 'main_loops != NULL' failed

### ISSUE THREAD

**Issue by danfe** [akiraux/Akira#403]
Currently, Akira would emit the following error upon quitting:

```(Akira:42704): Gtk-CRITICAL **: 16:37:46.457: gtk_main_quit: assertion 'main_loops != NULL' failed```

While seemingly harmless, it is still wrong.  I've googled it up and stumbled upon the following tangentially related [question+answer](https://stackoverflow.com/questions/36905118/code-cannot-exit-from-gtk-application-apparently-no-message-loops) on SO which suggests that `gtk_main_quit()` calls should be replaced with `g_application_quit()` calls instead.  Translated to Vala, it looks like the following change should be made to Akira's code:
```diff
--- src/Window.vala.orig
+++ src/Window.vala
@@ -153,7 +153,7 @@
         uint length = app.windows.length ();
 
         if (length == 0) {
-            Gtk.main_quit ();
+            app.quit ();
         }
     }
```
The same call exists in the `tests/canvas/test-main.vala` but I'd leave it for your discretion.

**Comment by albfan** [comment]
That's correct. Can you provide a PR?

**Comment by danfe** [comment]
Sorry, I don't grok PRs, they confuse me and make me cry.  What's wrong with the inline patch?

**Comment by albfan** [comment]
Just makes it easier to credit you on this. Will take care of details myself

**Comment by danfe** [comment]
> Just makes it easier to credit you on this.

Ah, I see, didn't know about this feature!  Thanks anyway, I care more about correct code than due credit. :-)
