### ISSUE TITLE
Bug when resizing rotated items in Artboards

### ISSUE THREAD

**Issue by Alecaddd** [akiraux/Akira#405]
## Expected Behavior
Resizing rotated items inside artbaords should behave exactly as it does for free items.

## Current Behavior
When resizing rotated items inside artboards the X and Y coordinates change unexpectedly.

## Possible Solution
This might be an issue due to our `compute_transform` method and how we handle painting of items inside artboards.

## Screenshots of the Problem
![artboard-item-resize](https://user-images.githubusercontent.com/2527103/90167065-0937de80-dd50-11ea-8b64-e835e9cc0b17.gif)

## Your Environment (for bugs)

- Akira Version: build from master
- OS Info: elementary OS 5.1.7

**Comment by tenzens** [comment]
Has anyone found out anything about this bug? I mean even removing the move method call from the scale method in AffineTransformations doesnt do anything. it still will move.

**Comment by Alecaddd** [comment]
I tried to work on this but didn't have much time, unfortunately.
Hopefully next week I'll be able to fix it.

**Comment by DevAlien** [comment]
A similar issue happens as well on the corner nobs, when the item is rotated, the corner nobs are crazy to use.
The one you are demostrating also does not work correctly when rotated, basically it moves just when the mouse goes left or right, if you move the mouse top/bottom nothing happens, but in reality it is going towards that direction. it seems like it does not take into account that the item is rotated.

**Comment by Alecaddd** [comment]
I know what's the problem with rotated objects in artboards.
Basically our artboard implementation resets the matrix transform of every child element and redraws it whenever something changes.
And we implemented a relative X and Y attribute to keep track of the coordinates since our approach clears the item's bounds.
When we resize, we interact with those relative coordinates instead of the correct matrix coordinates.
My objective is to rewrite the artboard to follow strictly the GooCanvas approach of parent > child relationship.

**Comment by Alecaddd** [comment]
@albfan Really great improvements on #483, good job.
Just a little thing, when resizing from the bottom right corner after rotating the item by 90deg, the item collapses on the first click on the nob.

![resize-glitch](https://user-images.githubusercontent.com/2527103/107126741-64add980-6866-11eb-8039-bf8f67087916.gif)

**Comment by albfan** [comment]
I check and is something related with all those fix_width, fix_height. Have to check with old implementation how we solve that.

**Comment by Alecaddd** [comment]
I fixed this thanks to the awesome examples provided by albfan.
Basically we rebuilt the Artboards to leverage the built-in CanvasGroup item of GooCanvas, and everything works like a charm.

![new-artboard-items](https://user-images.githubusercontent.com/2527103/108172736-05479900-70b2-11eb-904b-dee5ea23f26a.gif)

Coming soon in PR #485
