### ISSUE TITLE
Feature: Zoom should zoom to cursor, not center of view.

### ISSUE THREAD

**Issue by jdittrich** [akiraux/Akira#406]
## Expected Behavior
If I zoom via the mouse wheel, it should zoom to the cursor. So if an item is in the upper left corner of my screen and I place the mouse cursor there and zoom (ctrl+wheel) the cursor should stay on the item and the view port should zoom in on the item (The mechanics themselves have nothing to do with the item, it is just easier to imagine this way)

This is standard behavior in many applications, like inkscape and figma (though, to my annoyance, not in balsamiq)

## Current Behavior
Currently, the zoom is on center. This means the view is made "larger" while its center stays in place

## Possible Solution
Implement zoom to cursor. This means that the viewport needs to shift depending on mouse position while zooming. 

## Context
When you zoom in, you usually want to zoom in on something. The only way to do this right now is to pan the object of interest into the center of the viewport and then zoom. This is cumbersome. Zoom-to-cursor would just mean you place the cursor on what you are interested in and zoom in. 
(this is also coherent with pinch-to-zoom; while zoom to cursor pans the viewport in a way that your cursor stays on its position within the canvas/document, while pinch-to-zoom pans in a way so that your fingers or the point between them stays on the same position in the canvas/document)

## Zoom-To-Cursor in Inkscape

![Peek 2020-08-13 22-03](https://user-images.githubusercontent.com/3416487/90181645-15a05380-ddb1-11ea-9c0e-c3319637ac8b.gif)

- Akira Version: v0.0.12 - alpha
- OS Info: Ubuntu 20.04

**Comment by Alecaddd** [comment]
Hi, thanks for trying Akira.
Indeed this is a feature we want to implement before the beta, and we also want to implement the variation of zooming with the selected item at the center if done via keyboard.

Listed on bug #358
