### ISSUE TITLE
Please provide a png in /usr/share/icons/hicolor/256x256/apps/

### ISSUE THREAD

**Issue by probonopd** [akiraux/Akira#407]
## Expected Behavior

`/usr/share/icons/hicolor/256x256/apps/` contains a png file

## Current Behavior

`/usr/share/icons/hicolor/256x256/apps/` contains a svg file

## Possible Solution

(Also) put a png file into `/usr/share/icons/hicolor/256x256/apps/` (and the other fixed-resolution directories). Put the svg into `/usr/share/icons/hicolor/scalable/apps/` instead.

## Context

For AppImage I need a png icon rather than a svg icon. Converting it with ImageMagick gives less than ideal results.

https://github.com/probonopd/Akira/blob/3204fc2263a2ec4096ff4513c4bfd3cea8ab643f/.github/workflows/build.yml#L41-L42

## Screenshots of the Problem

![image](https://user-images.githubusercontent.com/2480569/90330805-2adad500-df9f-11ea-8328-ed35b4311bb1.png)

## Your Environment (for bugs)

- Akira Version: master
- OS Info: Xubuntu 18.04

**Comment by albfan** [comment]
I think move to scalable graphics would be the best idea, See https://gitlab.gnome.org/GNOME/Initiatives/-/issues/2

We can follow changes on meson.build here: https://gitlab.gnome.org/GNOME/gitg/-/commit/269e58d6e0544f8f0d27abe0400f52473ca800fc#a51079c0b033d41e18d9cfdc597a47eb4bdcbba5

What is not clear here is why AppImage needs only png files.

**Comment by probonopd** [comment]
> I think move to scalable graphics would be the best idea

A scalable icon can be provided in addition to the resultion-dependent png in `/usr/share/icons/hicolor/scalable/apps/`.

> What is not clear here is why AppImage needs only png files.

AppImage desktop integration tools use the icon as a thumbnail for file managers, and the XDG thumbnail spec does not allow scalable thumbnails but only png.

**Comment by albfan** [comment]
This is what I get from that convert command:

![com github akiraux akira](https://user-images.githubusercontent.com/220968/90332467-756b4a00-dfbd-11ea-9e48-0d607c6af830.png)

We can upload but if at some point we remove all that fixed scaled icons, you build script should just do the conversion correctly. I can see why it ends in a grayscale

**Comment by probonopd** [comment]
> We can upload

That would be highly appreciated. Thank you!

> I can see why it ends in a grayscale

I can't...

**Comment by bilelmoussaoui** [comment]
> > I think move to scalable graphics would be the best idea
> 
> A scalable icon can be provided in addition to the resultion-dependent png in `/usr/share/icons/hicolor/scalable/apps/`.
> 
> > What is not clear here is why AppImage needs only png files.
> 
> AppImage desktop integration tools use the icon as a thumbnail for file managers, and the[ XDG thumbnail spec](https://specifications.freedesktop.org/thumbnail-spec/thumbnail-spec-latest.html) unfortunately does not allow scalable thumbnails but only png.

Sounds like an issue that should be fixed by the integration provided by AppImage as an SVG icon works just fine.

**Comment by probonopd** [comment]
I tried to convert using ImageMagick and I got a wrong picture. Can you provide the correct one please?

**Comment by bilelmoussaoui** [comment]
rsvg-convert is more suited to convert a SVG to a PNG

**Comment by albfan** [comment]
@probonopd you can take that one I paste here. I'm providing a PR but is to keep only the svg icons

**Comment by probonopd** [comment]
> @probonopd you can take that one I paste here.

The one pasted above is somehow pixelated/resized.

**Comment by probonopd** [comment]
Using `rsvg-convert` works for me. Thank yo @bilelmoussaoui
