### ISSUE TITLE
Drop Shadow for Artboards, yes or no?

### ISSUE THREAD

**Issue by Alecaddd** [akiraux/Akira#410]
This is not an issue but an open discussion to consider the implementation of drop shadows for Artboards.

**Yes or No?**

Sketch has a light drop shadow for Artboards, but Figma and Adobe XD don't.
While it looks nice and helps further distinguish Artboards from other native elements, having that effect requires a forced redraw on the Canvas in order to prevent visual glitches.

This might affect the performance when dealing with big projects.
Is it really worth it?

**Comment by Alecaddd** [comment]
Since Artboards are basically CanvasItems, I will allow artboards to have drop shadow effects that can be handled by the user like a regular item.
No need to hard code the effect.

**Comment by Imerion** [comment]
I vote yes for having them, I agree it looks nice and helps distinguish them. But adding drop shadow effects as a user should be a decent compromise. :+1:
