### ISSUE TITLE
Akira install issue

### ISSUE THREAD

**Issue by kirantpatil** [akiraux/Akira#414]
## Expected Behavior
Akira should install without any error

## Current Behavior
error: REMOTE and REF must be specified

## Possible Solution
Don't know

## Steps to Reproduce (for bugs)

1. $ flatpak remote-add flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
2. $ flatpak install  akira

## Context
Install issue.

## Screenshots of the Problem

![Screenshot from 2020-08-18 13-25-50](https://user-images.githubusercontent.com/1178055/90486395-7f748080-e156-11ea-9b98-47d81eb488b8.png)

- Akira Version:
  Don't know

- OS Info:
$ cat /etc/issue
Ubuntu 18.04.4 LTS \n \l

**Comment by kirantpatil** [comment]
Installed using below command.

snap install --edge akira

**Comment by kirantpatil** [comment]
But original problem should be resolved or need to update the README with "snap install --edge akira" command.

**Comment by isneezy** [comment]
But wait I think your issue is still valid, you tried to install via flatpak and you got that error, as a workaround you installed via snap witch is totally unrelated to flatpak, correct me if I'm wrong. In this case the problem is not solved we need to make sure akira can be installed via flatpak.

**Comment by albfan** [comment]
Looks like @kirantpatil is using an old version of flatpak where it do not discover the app with a regexp

```
$ flatpak install akira
Looking for matches…
Found similar ref(s) for ‘akira’ in remote ‘flathub-beta’ (system).
Use this remote? [Y/n]: y
Found ref ‘app/com.github.akiraux.akira/x86_64/beta’ in remote ‘flathub-beta’ (system).
Use this ref? [Y/n]: y

com.github.akiraux.akira permissions:
    ipc    fallback-x11    wayland    x11    dbus access [1]

    [1] org.gtk.vfs.*


        ID                                               Branch            Op            Remote                   Descarga
 1. [✓] com.github.akiraux.akira.Locale                  beta              i             flathub-beta               15,5 kB / 256,9 kB
 2. [✗] org.freedesktop.Platform.openh264                2.0               u             gnome-nightly             < 1,5 MB
 3. [✓] com.github.akiraux.akira                         beta              i             flathub-beta                6,0 MB / 20,8 MB

Changes complete.
```

In that case:

    flatpak install com.github.akiraux.akira

should do the trick
