### ISSUE TITLE
Akira doesn't comply with the system GTK theme

### ISSUE THREAD

**Issue by Tooniis** [akiraux/Akira#421]
## Expected Behavior
Compliance with the system GTK theme (Adwaita in this case)

## Current Behavior
The theme from Elementary OS is used.

## Context
Since Akira's UI is GTK, it would be nice if it also integrated well into other environments that use GTK, like GNOME.

## Screenshots of the Problem
 

How Akira looks:
![Screenshot from 2020-08-23 18-19-10](https://user-images.githubusercontent.com/36982494/90980566-2c8f3480-e56d-11ea-92d8-bf204b62d94e.png)
How Adwaita looks:
![Screenshot from 2020-08-23 18-18-42](https://user-images.githubusercontent.com/36982494/90980567-3022bb80-e56d-11ea-8b6f-3d2b79733139.png)

## Your Environment (for bugs)

- Akira Version: 0.0.12
- OS Info: Arch Linux, GNOME 3.36

**Comment by albfan** [comment]
See #350
