### ISSUE TITLE
Cursor behaviour feels weird

### ISSUE THREAD

**Issue by Brin-o** [akiraux/Akira#422]
## Expected Behavior
When entering the artboard zone the cursor changes to some weird inverted anomaly that is pixelated. I expect it to stay the same unless it is trying to indicate me draggability/some function changing.

## Current Behavior
![akiracursorbug](https://user-images.githubusercontent.com/49071768/90986939-2443f300-e587-11ea-839c-4459f826a2df.gif)

## Steps to Reproduce (for bugs)
1. Install akira on Pop-os 20.04
2. Open akira
3. Move your mouse into the artboard area

## Context
I'm not sure why this happens and if it's a design decision (if so could you explain why?) but I personally find it very distracting. I used sketch and invision before for UX prototyping and at least there the mouse stays normal unless indicating something. I am not sure if this is something that was picked up from sketch.

## Your Environment (for bugs)
- Akira Version: v0.0.12 - alpha
- OS Info: POP OS 20.04

**Comment by Alecaddd** [comment]
This doesn't happen to me and I can't recreate the issue.
Obviously this is a big and not something done on purpose since it doesn't make any sense.
I will investigate further to see if it might be related to the 20.04 release, since I'm running 18.04

**Comment by Alecaddd** [comment]
How did you install Akira?
Did you compile it from source or got it via flatpak or snap?

**Comment by isneezy** [comment]
This issue was happening some time ago before alpha release on elementary os but now is gone.

**Comment by szul** [comment]
@Alecaddd I am running Pop OS 20.04 with Gnome version 3.36.3 and _cannot_ recreate this issue. Installed via flatpak.
