### ISSUE TITLE
Disparity between transform panel and whats actually viewed on canvas

### ISSUE THREAD

**Issue by isneezy** [akiraux/Akira#424]
## Expected Behavior
When moving the Canvas Item the X and Y position should be perfectly reflected on the Transform Panel

## Current Behavior
- The Transform panel dosent allow fractional values witch is fine
- When moving the Canvas Item around by using DND, it uses fractional values and it well represented by the Transform panel.

## Possible Solution
IDK, may be auto correct the fractional value Doing approximate calculation ?? 🤷‍♂️️

## Steps to Reproduce (for bugs)
1. Create an artboard
2. Create two rectangles and put them side by site (W: 20 H: 20)
3. With the transform panel set the Y position to something like 50
4. With you mouse try to align them on the Y axis (use zoom to make it easier)
5. You will see that at some point the Transform panel tells you that their are aligned but in fact they are not.

## Screenshots of the Problem
The first row is aligned using Transform Panel and The second row is aligned using DND.  Pay attention to the Y value on the Transform panel for the second row they have the same value but visually not aligned
![Screen record from 2020-08-25 15 21 35](https://user-images.githubusercontent.com/8999039/91180121-ae0ad200-e6e7-11ea-9cf6-10a47b7dff3c.gif)

## Your Environment (for bugs)
- Akira Version: Latest commint on master https://github.com/akiraux/Akira/pull/423
- OS Info:
Linux ivan-Latitude 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
NAME="elementary OS"
VERSION="5.1.7 Hera"
ID=elementary
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS 5.1.7 Hera"
LOGO=distributor-logo
VERSION_ID="5.1.7"
HOME_URL="https://elementary.io/"
SUPPORT_URL="https://elementary.io/support"
BUG_REPORT_URL="https://github.com/elementary/os/issues/new"
PRIVACY_POLICY_URL="https://elementary.io/privacy-policy"
VERSION_CODENAME=hera
UBUNTU_CODENAME=bionic

**Comment by Alecaddd** [comment]
Thanks for reporting this, I'm well aware of this issue which is tightly related to how we initially implemented the coordinate bindings to the transform panel.
I talked about this issue on bug #336, and I'm currently reworking the whole section.
