### ISSUE TITLE
Issue while building Akira

### ISSUE THREAD

**Issue by yasharya2901** [akiraux/Akira#426]
## Expected Behavior

It should have compiled without any error.

## Current Behavior

It is showing error.
## Possible Solution

No Idea

## Context

I was trying to build Akira from Source just for fun and while I ran the meson build command, it ended up with error showing the dependency json-glib-1.0 not found. So, I did sudo apt-get install json-glib-1.0 and it showed that I have already had this dependency installed.

## Screenshots of the Problem
 

![help alex help](https://user-images.githubusercontent.com/36362019/91334051-0c20dd80-e7ec-11ea-9d92-98b302777be4.png)

## Your Environment (for bugs)

- Akira Version: latest source code as downloaded at 26th August 2020 at around 10:00 PM IST
- OS Info: Ubuntu 20.04.1

**Comment by isneezy** [comment]
Not sure but try libjson-glib-dev

**Comment by albfan** [comment]
ubuntu use -dev packages for build. for any other missing dependency that's the answer

**Comment by yasharya2901** [comment]
Thanks @albfan! So, am I supposed to write -dev at the last while installing it?

**Comment by yasharya2901** [comment]
Plus, also write all these things in the documentations because I was scratching my head whole night about it.

**Comment by yasharya2901** [comment]
Okay, so it was this command which made it work: sudo apt-get install libjson-glib-dev

**Comment by yasharya2901** [comment]
Once again, thanks @albfan!

**Comment by albfan** [comment]
@yasharya2901 just a tip about developing. You can see in my comment on #428.

How to get a missing dependency depends on your distro, but is not a duty for a project, nor how to use the buildsystem, etc.
