### ISSUE TITLE
Instructions for building Akira on Ubuntu 20.04

### ISSUE THREAD

**Issue by codedracula4ec** [akiraux/Akira#428]
The instructions on readme and getting started section from 'contributing to akira' wasn't much helpful to me (might be because I'm a noob), so here it is what I had to do
## Instructions for building Akira on Ubuntu 20.04

To compile akira on ubuntu 20.04 you will need to install these dependencies:

- `libgtk-3-dev`
- `valac`
- [`io.elementary.vala-lint`](https://github.com/vala-lang/vala-lint) (need to compile)
- [`granite`](https://github.com/elementary/granite) (you will need to compile it, instructions below)
- `libgee0.8-dev`
- `libxml2`
- `libcairo2-dev`
- `gir1.2-goocanvas-2.0`
- `libarchive-dev`
- `libjson-glib-dev`
- `appstream-util`
- `meson`

### Install granite

**Install dependencies:**

- `libgirepository1.0-dev`
- `gobject-introspection`
- `libgee-0.8-dev`
- `libgtk-3-dev`
- `valac`
- `meson`
  

**Clone and build granite:**

[GitHub - elementary/granite: Library that extends GTK with common widgets and utilities](https://github.com/elementary/granite)

```shell
git clone https://github.com/elementary/granite.git
meson build --prefix=/usr
cd build
ninja install
```

### Install io.elementary.vala-lint

[GitHub - vala-lang/vala-lint: Check code-style of Vala code files](https://github.com/vala-lang/vala-lint)

**Install dependencies:**

- `libvala-0.48-dev`  
- `libglib2.0-dev`
- `valac`

**Clone and build:**

```shell
git clone https://github.com/vala-lang/vala-lint.git
meson build --prefix=/usr
cd build
ninja install
```

### Build and install Akira
```shell
meson build --prefix=/usr -Dprofile=default
ninja install
```

I've tested both on kubuntu 20.04.1 and ubuntu 20.04 and it works with some visual issues (white labels on light background). 'Use dark theme' doesn't work.
![image](https://user-images.githubusercontent.com/62944284/91373352-90736080-e7ec-11ea-94ef-62f4eab4dbb1.png)

**Comment by Alecaddd** [comment]
Would you be willing to do a PR to update the Contributing file?

**Comment by codedracula4ec** [comment]
I'll take a look at it. I'm new to github and git and programming in general

**Comment by albfan** [comment]
We understand that building can be overwhelming sometimes, but in general, this gets outdated really quick.

- You know you need meson and ninja due to files in project
- meson will tell you missing dependencies (normally)
- how those dependencies are retrieved depends on your distro (-dev packages on ubuntu, -devel on fedora)

You can add `elementary-theme` and `elementary-icon-theme` as needed packages (to fix your visual differences)

Document how to build on a specific distro is not a duty for a project really.

**Comment by codedracula4ec** [comment]
I understand. At least if someone gets stuck when compiling akira on ubuntu maybe this can help
