### ISSUE TITLE
Issue in Akira after building it in Ubuntu

### ISSUE THREAD

**Issue by yasharya2901** [akiraux/Akira#429]
## Expected Behavior

Akira should have looked like as it looks. The UI was different. Plus, the dark mode should have worked.

## Current Behavior

The UI is changed and the dark mode isn't working.
## Possible Solution

No Ideas!
## Context

I was trying to build Akira from the source because the snap package was buggy. I am new to building applications and understanding software. I am trying my best to learn in and out about how Akira works because I also want to contribute to it.

## Screenshots of the Problem
 

[bug2.zip](https://github.com/akiraux/Akira/files/5134254/bug2.zip)
(I have also restarted it but it didn't change the theme.)

## Your Environment (for bugs)

- Akira Version: Source code as downloaded on 26th Aug 2020 around 10 pm IST
- OS Info: Ubuntu

**Comment by Alecaddd** [comment]
Akira is based on the elementary OS theme and icons. If you don't have those, it'll look different.
We recommend to install Akira via the official Ubuntu snap to get the correct UI.

**Comment by yasharya2901** [comment]
Why it's not supposed to work with Ubuntu's theme?

**Comment by albfan** [comment]
@yasharya2901 there's elementary-theme and elementary-icon-theme available so you can see the app as we designed.

You can see many other design apps that has a different interface (blender, shotcut) Generally speaking, elementary is more concise and offers more icons for our needs.
