### ISSUE TITLE
Making a Perfect Circle when holding down shift

### ISSUE THREAD

**Issue by varlevi** [akiraux/Akira#439]
## Expected Behavior
I expected to have a perfectly round circle when holding down shift and draw the circle shape.

## Current Behavior
Holding shift does nothing.

## Possible Solution
I do not have experience coding in Vala unfortunately.
## Context
I can just change the size using the panel once I've draw the circle, but this is faster and more productive.
## Your Environment (for bugs)
- OS Info: Linux elementary-test 5.4.0-45-generic #49~18.04.2-Ubuntu SMP Wed Aug 26 16:29:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
NAME="elementary OS"
VERSION="5.1.7 Hera"
ID=elementary
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS 5.1.7 Hera"
LOGO=distributor-logo
VERSION_ID="5.1.7"
HOME_URL="https://elementary.io/"
SUPPORT_URL="https://elementary.io/support"
BUG_REPORT_URL="https://github.com/elementary/os/issues/new"
PRIVACY_POLICY_URL="https://elementary.io/privacy-policy"
VERSION_CODENAME=hera
UBUNTU_CODENAME=bionic
- Akira Version: 0.0.12

**Comment by Alecaddd** [comment]
You need to hold `CTRL` to fix the size ration of a shape during creation.
The `SHIFT` modifier will be reserved to allow resizing from the center point.

**Comment by varlevi** [comment]
Ahh... Thanks!

**Comment by isneezy** [comment]
@Alecaddd This is not working even when `ctrl` is pressed.
@varlevi what distro are you using and how did you install the app?

**Comment by varlevi** [comment]
@Alecaddd I'm using ElementaryOS and I installed to Akira via AppCenter
