### ISSUE TITLE
The application requires the runtime org.gnome.Platform/x86_64/3.36 which was not found

### ISSUE THREAD

**Issue by stnieder** [akiraux/Akira#442]
## Expected Behavior
I was trying to install Akira on my ClearLinux environment.

## Current Behavior
During the installation through the flathub store the following error shows up: `The application com.github.akiraux.akira/x86_64/beta requires the runtime org.gnome.Platform/x86_64/3.36 which was not found`. I have tried to install this specific version of org.gnome.Platform and also to restart the laptop, but that does not seem to solve my problem.

## Steps to Reproduce (for bugs)
1. Adding the flathub-beta repo through `flatpak remote-add flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo`
2. Trying to install Akira through `flatpak install akira`

## Your Environment (for bugs)
output of `uname -a && cat /etc/os-release`:
```
Linux clr-6b7511f6c7ff4239ab59a82043183384 5.8.9-986.native #1 SMP Mon Sep 14 11:14:07 PDT 2020 x86_64 GNU/Linux
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=33720
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"
BUILD_ID=33720
```

**Comment by albfan** [comment]
The solution is to install that platform, so please provide the output when you try to install akira.

**Comment by bilelmoussaoui** [comment]
Because you need to enable flathub `flatpak remote-add flathub https://flathub.org/repo/flathub.flatpakrepo` & then do a `flatpak update`

**Comment by bilelmoussaoui** [comment]
No it's not the required version of gnome shell. But the GNOME runtime.

**Comment by szul** [comment]
Corrected.

**Comment by bilelmoussaoui** [comment]
Thanks! I guess we can close this as the question was answered :)

**Comment by stnieder** [comment]
Tried it and it works now!!

**Comment by bakkerme** [comment]
I just wanted to add to this for anyone else reading this issue. I had the same error message, but I already had flatpak fully configured and the Gnome 3.36 Platform installed. Running with the `--no-deps` flag on the install worked like a charm and Akira runs correctly.
