### ISSUE TITLE
Some icons missing on Void Linux / JWM

### ISSUE THREAD

**Issue by reback00** [akiraux/Akira#444]
## Expected Behavior
Showing all icons on all places. The menus, toolbar, sidebar/pallete etc.

## Current Behavior
Some icons are missing on toolbar, menu, sidebar.

## Steps to Reproduce (for bugs)

1. Install Void linux with XFCE/JWM (I tested with Qogir, Papirus icon themes)
2. Then install with xbps-src:
```
sudo xbps-install xtools
git clone https://github.com/void-linux/void-packages
cd void-packages
./xbps-src binary-bootstrap
# Copy `akira` folder from <https://notabug.org/reback00/void-goodies/src/master/srcpkgs/akira> and put under `srcpkgs` folder, then...
./xbps-src pkg akira
xi akira
```
3. Running Akira should show up with some icons missing

## Context

Well, I wanted to [make a package](https://notabug.org/reback00/void-goodies/src/master/srcpkgs/akira) for Void Linux repos, plus use it for myself. I found out about Akira from @Alecaddd 's LBRY channel and was interested about it. Void Linux does not allow dev versions on their repo, so maybe not now, but when 1.0 releases I would be able to submit it. But I'm open to anyone wanting to take over. Please let me know if anyone official from the project wants to maintain the future submission of the package to Void repos.

btw... terminal output is empty on startup. So not getting much hint.

## Screenshots of the Problem
 

![akira-01](https://user-images.githubusercontent.com/51861250/94025838-c5b6a280-fdda-11ea-97fb-24b42537b908.png)

## Your Environment (for bugs)

Nothing special...
```
$ uname -a && cat /etc/os-release
Linux [redacted] 5.8.10_1 #1 SMP Fri Sep 18 09:39:06 UTC 2020 x86_64 GNU/Linux
NAME="void"
ID="void"
DISTRIB_ID="void"
PRETTY_NAME="void"
```
- Akira Version: v0.0.13 - alpha
- OS Info: Void Linux

**Comment by albfan** [comment]
You need elementary theme and elementary icons.

**Comment by reback00** [comment]
@albfan Thanks, the icons are showing after I installed `io.elementary.icons` package on Void.

I think this should be included somewhere in the readme, in case someone else needs this info. Especially someone building from source on a non-elementary distro.

**Comment by albfan** [comment]
Yes. As it is a hard dependency probably we need to check something. But maybe as a warning only as the UX is not as expected but the app still works.

Have to check around for this kind of checks for themes

**Comment by isneezy** [comment]
Maybe we should reference this on the README.md file for those who build by themselves. What you think @albfan ?

**Comment by albfan** [comment]
We have a section `### Install Dependencies` so mention there elementary theme and elementary icon makes sense @isneezy .
`

**Comment by isneezy** [comment]
@albfan I've created [this PR](https://github.com/akiraux/Akira/pull/447), hoping it will help other people and no other issues of this kind will be raised.
