### ISSUE TITLE
Text not visible when dropped to Artboard

### ISSUE THREAD

**Issue by ni-ku** [akiraux/Akira#455]
## Expected Behavior
When Text is dropped to an Artboard it should remain visible.

## Current Behavior
When Text is dropped to an Artboard it is getting white Color/ isn't rendered.

## Screenshots of the Problem
![text_white_when_dropping_to_artboard_bug](https://user-images.githubusercontent.com/13109811/97035859-3e8a5500-1567-11eb-8912-593bda7f5c9a.gif)

## Your Environment (for bugs)
- Akira Version: 0.0.13
- OS Info: Arch

**Comment by Alecaddd** [comment]
Hi, thanks for the report. This is a known issue due to the fact that we're not implementing the text tool until later during the development cycle.
I'll keep this bug open just for tracking.
Cheers
