### ISSUE TITLE
Top Menu Bar

### ISSUE THREAD

**Issue by stefanusayudha** [akiraux/Akira#457]
## Expected Behavior
When i press Shift+F11 on elementary,, window will forced to fullscreen..

## Current Behavior
The TOP Menu Bar then go disapear when in fullscreen mode..

## Possible Solution
maybe redrawing the top pannel when it enter fullscreen can solve the problem

## Screenshots of the Problem
This is the normal view
![Screenshot from 2020-10-31 00-26-32](https://user-images.githubusercontent.com/20390800/97737761-08714600-1b10-11eb-9b3c-539a21d975cb.png)

This is the fullscreen view
![Screenshot from 2020-10-31 00-26-40](https://user-images.githubusercontent.com/20390800/97737781-0c9d6380-1b10-11eb-99d8-92aafa5a7b56.png)

## Your Environment (for bugs)

- Akira Version: 0.0.13 alpha
- OS Info: Elementary OS

**Comment by TomaszGasior** [comment]
This may be related to https://gitlab.gnome.org/GNOME/gtk/-/issues/2795
