### ISSUE TITLE
Opening in Openbox results in large black border around window

### ISSUE THREAD

**Issue by PPiinngg** [akiraux/Akira#459]
there's a HUGE border around the window when run in openbox. don't have any other wm's to test in but i assume this isn't intended behavior.
![image](https://user-images.githubusercontent.com/38050295/100563399-3801a280-32b6-11eb-9cd3-13b982418b52.png)

not the worst thing in the world, but rather annoying.

latest git build from the AUR (0.0.13.r11.ga766d)
manjaro 5.9.11

**Comment by Alecaddd** [comment]
This is a problem with the elementary stylesheet, not Akira.
The new stylesheet version that will come out with elementary OS 6 won't have this issue.
elementary/stylesheet#843
