### ISSUE TITLE
Issue Not related to Akira

### ISSUE THREAD

**Issue by lifeiscontent** [akiraux/Akira#463]
Hi @Alecaddd first off I'd like to say thank you for all the amazing work you've done.

I am having a very hard time trying to figure out how to find the right resources to learn the ecosystem of Elementary OS.

Any help with this would be greatly appreciated. I'm trying to create my first app for the Elementary OS AppCenter

any ideas on when you might continue working on your tutorials?

Thanks!

**Comment by nisrulz** [comment]
Have you checked this: https://developer.elementary.io/

**Comment by lifeiscontent** [comment]
@nisrulz Yep, I'm traditionally a Web developer. I've never really spent any amount of time with C, or any compiled language for that matter.

I'm still getting the hang of learning how to read valadoc as it's pretty overwhelming for a beginner. The course @Alecaddd put on YouTube was a great start but unfortunately he has yet to cover anything on Storage. E.g. how to populate a list box with a model, how that data flow works with CRUD, and how to persist data long term even after the user has closed the app.

**Comment by albfan** [comment]
Akira and many elementary apps are written on vala:

https://developer.gnome.org/gnome-devel-demos/stable/beginner.vala.html.en

Which is an abstraction that file creates C files.

Teach to code on vala or for elementary is out of scope for Akira.

GNOME community has an initiative to learn gtk app basis

https://wiki.gnome.org/Newcomers

You can get in contact by IRC or matrix:

https://wiki.gnome.org/Community/GettingInTouch/IRC
