### ISSUE TITLE
Add Ctrl-Z and Ctrl-Y functionality

### ISSUE THREAD

**Issue by ApolloDev0** [akiraux/Akira#481]
I noticed There wasn't a Ctrl-Z and Ctrl-Y implementation available in akira so i couldnt revert back to previous state im not sure if you have this  in another way but i think this would be a nice general feature, thanks!.

im runnin akira on elementary os linux 64 bit

**Comment by Alecaddd** [comment]
Hi, thanks for trying Akira.

The action history feature hasn't been implemented yet, but it will available before the beta release (right now we're in the alpha cycle).
You can follow discussion of this feature here: #263
And check the full list of upcoming features here: #358

Closing this as duplicate.

**Comment by ApolloDev0** [comment]
okay thanks!
