### ISSUE TITLE
Examples of linux gui created using Akira

### ISSUE THREAD

**Issue by seekingdeep** [akiraux/Akira#487]
@Alecaddd @giacomoalbe @albfan @bilelmoussaoui 
H there,
i am looking for examples of Akira's possibilities, are there any examples of gui's created using Akira

**Comment by Alecaddd** [comment]
This is more a Discussion than an issue.
You can check #472 for some examples, but Akira is still in Alpha so a lot of features are not available and it's very limited in what it can do.

For the future, please avoid pinging everyone. Writing a message already sends us a notification, no need to ping all the contributors.
