### ISSUE TITLE
Make the Canvas a droppable area for external files

### ISSUE THREAD

**Issue by Alecaddd** [akiraux/Akira#491]
## Expected Behavior
The Canvas should be a droppable area for external files the users want to use inside Akira.
An initial and limited support might include:
- Akira files, which should load the file if the current window is empty and unedited, or ask the user to replace it, or open a new window.
- Raster images (PNG, JPG, GIF (not animated)).
- SVGs (temporarily imported as raster version, for later including proper conversion and vector manipulation).

In the future, we might start supporting also the dropping of PDFs and text, if we can guarantee text editability and support for multiple pages. 

## Current Behavior
Nothing happens.

**Comment by albfan** [comment]
Probably we can use this example to implement it.

After receive the file, is up to us to raster, import or load

**Comment by Abdallah-Is-A-Coder** [comment]
Hi @Alecaddd, I am a web & software developer an also a designer. 
I have been following this project for like 3 months and i really like what are u trying to make so. 
I am willing to help develop Akira
