### ISSUE TITLE
Unable to click on a Selection Nob when zoomed in

### ISSUE THREAD

**Issue by Alecaddd** [akiraux/Akira#498]
## Expected Behavior
Selection Nob should work at every zoom.

## Current Behavior
If you zoom in passed 1200%, the Selection Nobs on the left or right edges are not selectable anymore.
It seems that the corner nobs always work.

It's also a bit hard to reproduce and it doesn't happen every time.
Sometimes it happens if you select the item first at regular zoom, then you zoom in, resize it from the corners, and then try to select the Nob at the edge.
Tricky.

**Comment by Alecaddd** [comment]
@albfan any insights on this? Can you reproduce this issue?

**Comment by albfan** [comment]
Seems there're calculations failing at high zoom:

https://user-images.githubusercontent.com/220968/109383642-ffd72380-78e7-11eb-97be-bcced5c8be0c.mp4

But I draw rectangles at 100% and zoom 1200% and cannot reproduce the problem.

**Comment by mbfraga** [comment]
Figured out why this was: In the mouse events in the canvas, the values were being rounded--which meant that the events were at a pixel precision and the hit testing was failing. I fixed this in a PR.
