### ISSUE TITLE
Flathub refuses to install Akira because of missing runtime, even if everything is already installed

### ISSUE THREAD

**Issue by lonelynerd** [akiraux/Akira#503]
## Expected Behavior

The Akira package should be downloaded and installed as expected with any other Flatpak apps.

## Current Behavior

When `$ flatpak install akira` is inputted, the following message appears : `error: The application com.github.akiraux.akira/x86_64/beta requires the runtime org.gnome.Platform/x86_64/3.36 which was not found`, even if the GNOME runtime is already installed ( `org.gnome.Platform//3.36` , `org.gnome.Platform//3.36beta` )

## Steps to Reproduce (for bugs)

1. install `org.gnome.Platform//3.36`
2. try to install Akira using `flatpak install akira`

## Your Environment (for bugs)

- Akira Version: 0.0.13 ( installation attempt using Flatpak )
- OS Info:

Pop_OS 20.10 Intel version
GNOME version : 3.38
Flatpak version : 1.8.5

**Comment by Alecaddd** [comment]
@bilelmoussaoui, any hint on what the problem might be?

**Comment by bilelmoussaoui** [comment]
That's probably because however you installed the gnome runtime, you installed it as --system and you're trying to install akira as --user here. You should do `flatpak install com.github.akiraux.akira --user` which should work fine.

**Comment by albfan** [comment]
Yes, there's some kind of mix on that. flatpak detects your runtime as installed (so not need to install again) but app installation do not see the runtime.

Happens to me from time to time.

**Comment by lonelynerd** [comment]
Alright, after some try & errors, I finally found what's wrong. You actually have to add the repo as `--user`. After that, it should work just fine.
