### ISSUE TITLE
Update Snap to use Goocanvas 3

### ISSUE THREAD

**Issue by Alecaddd** [akiraux/Akira#517]
## Expected Behavior
The Snap should use the Goocanvas 3 branch like the Flatpak.

## Current Behavior
The Snap uses Goocanvas 2.

## Possible Solution
Update the `snapcraft.yaml` file to fetch, build, and install goocanvas 3

**Comment by Alecaddd** [comment]
Pinging @popey, hoping he has some time to look into this :pray:

**Comment by Abdallah-Moh** [comment]
I think it is this line
https://github.com/akiraux/Akira/blob/83c7b03b1a29274d46a4811c94ff4a8be4e050dd/build-aux/snap/snapcraft.yaml#L70
