### ISSUE TITLE
Add a panel for adding different art-board sizes like for mobile, web or tablet

### ISSUE THREAD

**Issue by Abdallah-Moh** [akiraux/Akira#547]
## Expected Behavior

Add an option that will allow the user to add real device sizes like in figma

## Screenshots of the Request
 

![Screenshot from 2021-04-09 19-06-37](https://user-images.githubusercontent.com/77546233/114216132-cb369d00-9966-11eb-8ad7-c51b71a7048b.png)

**Comment by LucileDT** [comment]
I think this should be moved into Discusions

**Comment by Abdallah-Moh** [comment]
It is already there

**Comment by Alecaddd** [comment]
@LucileDT is right, this is not an issue but a discussion.
I'll convert it.
