### ISSUE TITLE
Something wrong with css theme

### ISSUE THREAD

**Issue by gavr123456789** [akiraux/Akira#551]
Some icons are white, text on rigth layer panel too, the color picker only has an outline of the selected color:  
![image](https://user-images.githubusercontent.com/30507409/114299597-e0294280-9ac4-11eb-84a1-4a0e5c16534e.png)  
"Use Dark Theme" changes only color of preferences headerbar:  
![image](https://user-images.githubusercontent.com/30507409/114299648-1ebefd00-9ac5-11eb-9c25-1810a4c368c2.png)
Changing the GTK theme or icon theme has no effect.
Desktop: GNOME 40

**Comment by Alecaddd** [comment]
Did you compile it from source or via flatpak?
We're using the new elementary OS 6 theme and forcing it into the application.

**Comment by albfan** [comment]
I'm sure this is related with lack of elementary theme. Building on host I have it available as package on Arch Linux, but not sure for other distros

**Comment by Abdallah-Moh** [comment]
What Distro are you Using

**Comment by Abdallah-Moh** [comment]
@gavr123456789 If you are not using elementary os and compiled the app from source you will need to install and compile 

- Elementary os Icons : https://github.com/elementary/icons
- Elementary os theme : https://github.com/elementary/stylesheet

**Comment by Alecaddd** [comment]
@gavr123456789 this should be fixed with the latest merges to the flapak file.
Can you confirm?

**Comment by Leon0402** [comment]
Can confirm these issues with the latest release on Arch Linux. 

The package includes icons and theme:
https://aur.archlinux.org/packages/akira

**Comment by Alecaddd** [comment]
Anyone has the ability to test PR #590 and confirm that it fixes this problem?
