### ISSUE TITLE
Build failed in Gnome Builder

### ISSUE THREAD

**Issue by Alecaddd** [akiraux/Akira#552]
I'm trying to build Akira on Pop OS 20.04 via Gnome Builder.

The build fails with this error message:
`Failed to init: Unable to find app io.elementary.BaseApp version juno-20.08`

@bilelmoussaoui, any idea if this can be fixed?

**Comment by bilelmoussaoui** [comment]
You need to install `flatpak install flathub io.elementary.BaseApp//juno-20.08`, Builder doesn't auto-install base apps I think, hopefully won't be needed once there's a elementary sdk/runtime

**Comment by Alecaddd** [comment]
Lovely, thanks.
