### ISSUE TITLE
Errors when trying to add an image with long width and short height

### ISSUE THREAD

**Issue by Alecaddd** [akiraux/Akira#567]
## Expected Behavior
Images should be normally added no matter of their size.

## Current Behavior
If an image with a long width and short height is added via the image tool, multiple errors are generated and the UI glitches.

## Possible Solution
This is probably caused by the default sizing added to the image on creation and the pixbuf sizing happening to maintain the original image ratio.

## Steps to Reproduce (for bugs)
1. Download this image: 
![Screenshot from 2021-04-07 20-19-01](https://user-images.githubusercontent.com/2527103/115983573-d4269180-a556-11eb-9f69-81f35c314b57.png)
2. Add it through the image tool.

**Comment by Abdallah-Moh** [comment]
The image tool has a lot of bugs
Like when I save an akira file and reopen it sometimes the image gets resized to 1 and when I resize it back the image have the wrong ratio and when I change the width of the image through the left panel the height of the images change but in the left panel the height is still the same number as before unless I re select the image I know how to fix it when the user changes height we get the selected item width and height and set them to the inputs of the left panel

**Comment by Abdallah-Moh** [comment]
There is one more but it will be hard to explain it through text so I will create an issue with gifs

**Comment by Abdallah-Moh** [comment]
@Alecaddd  I think to fix this we will need to check if the height is less than 1 when calculating the pixpuf and if the height is less than 0 set it to 1 then recalculate its width then set them to the CanvasImage this problem happens when the height is less than 1 which when converted to int the height will be 0

**Comment by Abdallah-Moh** [comment]
@Alecaddd
```
var adjusted_height = 2 * size.height / size.width;
print("Adjusted Height: "+adjusted_height.to_string()+"\n");
var adjusted_width = 2 * size.width / size.height;
print("Adjusted Width: " + adjusted_width.to_string());
```
I replaced the code which sets the width = 2; with the code above
to stop any errors while testing
an I got 
![image](https://user-images.githubusercontent.com/77546233/119473671-ae55fd80-bd4b-11eb-9589-d7cb15b8c6ac.png)
and as you see when we set the width to 2 the height is a decimal less than 1 which int will convert it to a 0 and the other line is 
the width if the height was 2
