### ISSUE TITLE
Create elementary OS 6 flatpak manifest

### ISSUE THREAD

**Issue by hanaral** [akiraux/Akira#570]
## Current Behavior

Currently there isn’t a flatpak manifest for building Akira using the new Odin flatpak SDK - which is necessary for Odin AppCenter.
## Possible Solution

~~You can grab the `daily` version of `io.elementary.Sdk` from the elementary flatpak repo with `flatpak remote-add --if-not-exists elementary https://flatpak.elementary.io/elementary.flatpakrepo `. Bear in mind that you *have to* use the `daily` package, because the release 0.1.0 is missing the inherited GL extensions.~~

apologies if this is already an open issue, but I couldn’t find one specifically about using the new Sdk that released to everyone a few days ago

#### Edit:
You can add the new AppCenter repo with `flatpak remote-add --if-not-exists appcenter https://flatpak.elementary.io/repo` (remove the original `elementary` repo if you prev. had it). I should also point out that all the new beta images have had it built in for a while.

**Comment by Alecaddd** [comment]
The AppCenter dashboard is not yet updated to allow releasing the flatpak via their automated system.
I tested the whole process with `sequeler` and it works, but I'm still waiting for the AppCenter to allow publishing apps via the Huston dashboard.

**Comment by hanaral** [comment]
Yeah, screenshots and page colour aren't functioning either I think (not that it's a no.1 priority)
Also sorry for spamming you on twitter lol

**Comment by hanaral** [comment]
@Alecaddd Is it OK to close this now that there is a proper AppCenter YAML?

**Comment by Alecaddd** [comment]
Yup, thanks for the reminder.
