### ISSUE TITLE
Cannot maximize window in Elementary OS 5.1

### ISSUE THREAD

**Issue by juanfabiorey** [akiraux/Akira#584]
## Expected Behavior

The maximize button doesn't work as expected. I click it and do nothing.

## Steps to Reproduce (for bugs)

1. I installed Akira from Elementary App Center
2. when I open the application, I try to maximize and the button it doesn't work.
3. After closing and opening several times, I don't know how, it was maximized. but now, it does not return to the previous size when I click the same button.
4. Testing, with the right mouse button on the maximize button, I used the option "rezise" and I was able to make the window smaller. Again, impossible to maximize. Attached video of the problem.
## Screenshots of the Problem
 

[https://youtu.be/dVFF4tnQkyA](https://youtu.be/dVFF4tnQkyA)

## Your Environment (for bugs)

Linux <my-laptop-name>  5.4.0-72-generic #80~18.04.1-Ubuntu SMP Mon Apr 12 23:26:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
NAME="elementary OS"
VERSION="5.1.7 Hera"
ID=elementary
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS 5.1.7 Hera"
LOGO=distributor-logo
VERSION_ID="5.1.7"
HOME_URL="https://elementary.io/"
SUPPORT_URL="https://elementary.io/support"
BUG_REPORT_URL="https://github.com/elementary/os/issues/new"
PRIVACY_POLICY_URL="https://elementary.io/privacy-policy"
VERSION_CODENAME=hera
UBUNTU_CODENAME=bionic

- Akira Version:
- OS Info:

**Comment by LucileDT** [comment]
Hello, thanks for opening an issue! Could you please fill it with needed information so we will be able to track your problem and fix it? :slightly_smiling_face:

**Comment by Alecaddd** [comment]
This feels more of an elementary OS specific issue.
elementary 5.1 is also very close to be end of life and we haven't released the new Akira version there in a while.
We're waiting for elementary os 6 to get out of beta to publish the new version on the appcenter.
Closing this as it's out of scope.
