### ISSUE TITLE
Add animation

### ISSUE THREAD

**Issue by Isksks** [akiraux/Akira#613]
### Discussed in https://github.com/akiraux/Akira/discussions/612

<div type='discussions-op-text'>

<sup>Originally posted by **Isksks** June 21, 2021</sup>
Animation is a necessity for Ui and graphics designers
We should add this features
figma smart animation type thing
#612 #602 </div>

**Comment by Alecaddd** [comment]
Please, don't spam the repo by opening both issue and discussion.
I can convert a discussion into an issue later on once we start working on it.
Closing this as it's currently unnecessary.
