### ISSUE TITLE
Unable to set individual border radius for rectangles.

### ISSUE THREAD

**Issue by DuttaAB-dev** [akiraux/Akira#614]
Unable to set the border radius of a rectangle for individual corners. Changing the values does nothing and clicking anywhere inside the canvas resets the value to 0. Here is a sample video of the issue that I am facing. 

https://user-images.githubusercontent.com/61903332/123060312-3d783300-d428-11eb-927f-2596422d0e2f.mp4

Running Akira 0.14 installed from flatpak beta on Pop!_OS 21.04 under wayland.

**Comment by albfan** [comment]
That needs a PR on goocanvas.

See #259

**Comment by Alecaddd** [comment]
Hi, this is a known missing feature that we're working on in #259 

Take a look at the beta wishlist to check which features are available and which are missing. #358

**Comment by DuttaAB-dev** [comment]
Can you please explain, if you have enough time, why the MR for goocanvas was closed?

**Comment by albfan** [comment]
Feature is already impleme red on goocanvas 3.0

See https://gitlab.gnome.org/GNOME/goocanvas/-/commit/af294a7cfa5614cedc5c22e7696bf71fb13795a8
