### ISSUE TITLE
System-related interaction buttons and resizers kept in tiling WMs

### ISSUE THREAD

**Issue by Arteneko** [akiraux/Akira#620]
## Expected Behavior

The system-related interaction buttons (like minimize, maximize, close) and the resize bar surrouding the window shouldn't be shown on a window manager that doesn't suppoort them (e.g. i3, or bspwm).

## Current Behavior

They're both shown and semi-active: the close button effectively closes the window, but the maximize button simply hides the resize zone, and the minimize button does nothing.

## Possible Solution

I don't know enough about GTK, but isn't there a way to let it handle those actions instead of re-implementing them?

## Steps to Reproduce (for bugs)

With a tiling WM, like i3 or bspwm, simply start the software.

## Screenshots of the Problem

![image](https://user-images.githubusercontent.com/23583792/124249733-71d4a900-db24-11eb-9977-aee60e0fb412.png)

The surrounding white bar (resize zone) and the three right buttons shouldn't be shown.

## Your Environment (for bugs)

- Akira Version: 0.0.14-1
- OS Info: Arch-Linux, BSPWM window manager

**Comment by Abdallah-Moh** [comment]
@Arteneko From where did you install app
- Source
- Flatpak
- Snap

**Comment by Arteneko** [comment]
I used [the AUR package](https://aur.archlinux.org/packages/akira/), which seems to be a compiled version of the source code.

I neither have Flatpak nor Snap.

**Comment by Abdallah-Moh** [comment]
@Arteneko Do you have elementary stylesheets and icons installed

**Comment by Abdallah-Moh** [comment]
From the Image: I guess you have the icons but not the theme because the layer panel does not have borders

**Comment by Abdallah-Moh** [comment]
@Arteneko Could you explain the issue more what I understood is that the window manager you have does not support maximizing and minimizing. am I right?
gtk uses your systems controls layout for the window controls so this means that other gtk apps have the same issue does they?

**Comment by Arteneko** [comment]
My window manager doesn't support either options in a standard way indeed.

Other GTK softwares don't have this issue because they don't show those actions at all, which is my request.

**Comment by Abdallah-Moh** [comment]
Could you tell me a name of one of the gtk apps that does not have this issue and did not get preinstalled with system

**Comment by Abdallah-Moh** [comment]
and send a screen shot of it if possible

**Comment by Arteneko** [comment]
Sublime Merge doesn't have it.

![image](https://user-images.githubusercontent.com/23583792/124366950-cfb3de80-dc53-11eb-934f-4f19a45192ad.png)

Glade and Lutris seems to have it though.

**Comment by Abdallah-Moh** [comment]
`Sublime Merge` is not gtk as I know. So this issue is not with akira it is related to gtk akira cannot detect the window manager you have

**Comment by Arteneko** [comment]
Doesn't the GTK framework provide a way to do feature detection to toggle the display of those actions?

**Comment by Abdallah-Moh** [comment]
Akira cannot detect if your window manager supports maximizing and minimizing

**Comment by Abdallah-Moh** [comment]
GTK follows your system controls layout so if you tweak your arch installation you can hide the minimize and maximize buttons.
Like in elementary os the default layout does not have a minimize button and GTK hides it because this is not the systems layout settings

**Comment by Alecaddd** [comment]
Hi @Arteneko, thanks for trying Akira.
I'm not sure GTK has the ability to detect the window manager and adapt the controls based on it.
Nonetheless, we currently don't have the resources to support anything other than X11, and in the future Wayland.
We're more than happy to accept a PR from someone more knowledgeable than us to fix this problem, but for now I'm gonna close this issue and flag it as out of scope since we're not actively targeting BSPWM.

**Comment by Arteneko** [comment]
(just as side note, BSPWM is a window manager for X11)

**Comment by Alecaddd** [comment]
> (just as side note, BSPWM is a window manager for X11)

And that tells you how little I know about these things :sweat_smile: 
If you find any solution or code snippets we could put inside Akira, please add it here and I'll be more than happy to reopen this issue and try a fix.
