### ISSUE TITLE
[Suggestion] Add "Copy", "Paste", etc. features

### ISSUE THREAD

**Issue by Sav22999** [akiraux/Akira#622]
## Expected Behavior

With "Ctrl+C", etc. or also with "Right mouse-click">"Copy"/"Paste"/"Cut"/... you should able to copy/paste/cut etc. an object (rectangle, circle, etc.)

## Current Behavior

This feature doesn't exist

**Comment by Abdallah-Moh** [comment]
This is in our beta wishlist https://github.com/akiraux/Akira/issues/358

**Comment by Sav22999** [comment]
@Abdallah-Moh Sorry, I searched in the "Issues" and I didn't find anything, so I thought to open it. So I can close this isse
