### ISSUE TITLE
Error on install from flathub

### ISSUE THREAD

**Issue by nicolalandro** [akiraux/Akira#624]
## Expected Behavior
When I follow the flathub guide it install Akira

## Current Behavior
The install instruction explained generate error

## Possible Solution
I think that flatpack need something with two dot like for godot `flatpak install --user flathub-beta org.godotengine.Godot`.
So possible solutions is the following:
```
flatpak remote-add flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
flatpak install akira < This line is wrong, it should seams the following
flatpak install flathub-beta org.SOMETHING.Akira
```
But what is that extensive name of Akira flathub-beta? 

## Steps to Reproduce (for bugs)
1. flatpak remote-add flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
2. flatpak install akira
Results
```
...
error: REMOTE and REF must be specified
```

## Your Environment (for bugs)
I'm on LinuxMint 19.3 Cinnamon, Flatpak 1.0.9

- Akira Version: unknown
- OS Info: LinuxMint 19.3 Cinnamon

**Comment by albfan** [comment]
Working on 

```
$ flatpak --version
Flatpak 1.11.2
```

Probably you need to adapt for old flatpak version or update flatpak

**Comment by nicolalandro** [comment]
I find it manually, to install it I must exec that:
```
flatpak install flathub-beta com.github.akiraux.akira
```

**Comment by albfan** [comment]
Where you get this instructions: I'm just aware of my own tweet where I publish exactly that:

https://twitter.com/albfanjul/status/1301477685701619712?s=20
