### ISSUE TITLE
Ghost rectangle bug when Alt + Tab

### ISSUE THREAD

**Issue by renk-0** [akiraux/Akira#627]
## Expected Behavior
When selecting a rectangle and Alt + Tab, it should do nothing

## Current Behavior
A blue square appears and does not disappear, and if I move the square and do Alt + Tab, another squares get stuck on the canvas and so on.

## Possible Solution
I have already partially solved it, the ghost square still stuck there when Alt + Tab, but when creating another ghost square it removes the last one 

**src/Lib/Canvas.vala:**
```diff
public void toggle_item_ghost (bool show) {
    // If no items is selected we can't show anything.
    if (selected_bound_manager.selected_items.length () == 0) {
        return;
    }

    // Temporarily get the first item until multi select is implemented.
    var item = selected_bound_manager.selected_items.nth_data (0);

+   if (ghost != null) {
+      ghost.remove ();
+   }

    if (show) {
        ghost = new Goo.CanvasRect (
            null,
            item.coordinates.x1, item.coordinates.y1,
            item.coordinates.x2 - item.coordinates.x1, item.coordinates.y2 - item.coordinates.y1,
            "line-width", 1.0 / current_scale,
            "stroke-color", "#41c9fd",
            null
        );
        ghost.set ("parent", get_root_item ());
        ghost.can_focus = false;
        ghost.pointer_events = Goo.CanvasPointerEvents.NONE;
-       return;
    }

-   if (ghost != null) {
-       ghost.remove ();
-   }
}

```

## Steps to Reproduce (for bugs)

1. Create a square
2. Select the new square
3. Press Alt + Tab

## Context
I was trying to change song from Youtube while testing akira and this happened   

## Screenshots of the Problem
![imagen](https://user-images.githubusercontent.com/68037616/125862248-18cfed1e-2476-4889-bc8a-c953c03014c3.png)

## Your Environment (for bugs)

- Akira Version: v0.0.14 - alpha
- OS Info:  
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by Alecaddd** [comment]
Yeah, this is annoying.
I think we should add tweak the shortcut to trigger a `toggle_item_ghost (false)` if any other key is pressed alongside the `ALT` modifier.
That should clear any potential ghost item in case the user is using OS shortcuts.

**Comment by mbfraga** [comment]
In the future hopefully this will just be drawn on top, so it will correctly survive without having to do manual object management :P

**Comment by Alecaddd** [comment]
This doesn't happen in the new default `main` branch.
