### ISSUE TITLE
Installing dependencies

### ISSUE THREAD

**Issue by jukhamil** [akiraux/Akira#628]
Is there an efficient way to install all the necessary dependencies?

I considered searching for them and installing them all at once with Aptitude. But I couldn't find the package "gtk" there.

Is it necessary to research installation instructions individually for each dependency or is there an easier way to do it?

**Comment by albfan** [comment]
As counterintuitive this might sound, that is offtopic for this project.

See this is distro specific. how your distro name the package gtk, if it split development files and binaries, if they provide debug symbols.

As an example for ubuntu normally you put a lib as prefix and -dev as suffix:

https://packages.ubuntu.com/bionic/libgtk-3-dev

In arch linux is just gtk3 for binary and devel files:

https://archlinux.org/packages/extra/x86_64/gtk3/

We cannot document all the distros out there and how to get dependencies, as long as meson complains about a faulty dependency, you need to find out how to get in your distro (see akira can run even on windows)

Anyway, you can use flatpak if you want to run akira in a sandbox that downloads all for you: https://twitter.com/albfanjul/status/1301477685701619712

    flatpak remote-add flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
    flatpak install com.github.akiraux.akira

Let us know if that clarifies your question (closing this issue if so)

**Comment by jukhamil** [comment]
Thank you.
I installed flatpak via apt install flatpak and it seems to be installed.
When I call the remote-add command above it returns "segmentation fault".

Is there something the matter with the repository address above, perhaps?

Thanks very much.

**Comment by albfan** [comment]
Probably related with https://github.com/flatpak/flatpak/issues/3612

Try to run with `--user`

**Comment by danfe** [comment]
> Is there an efficient way to install all the necessary dependencies?

Yes, there is: install Akira as a package provided by your distribution which would naturally install all needed dependencies.  This would also take care of future upgrades, uninstall, etc.

If your distribution does not provide Akira packages, consider switching to one that does (e.g. FreeBSD).

**Comment by Alecaddd** [comment]
> Yes, there is: install Akira as a package provided by your distribution which would naturally install all needed dependencies. This would also take care of future upgrades, uninstall, etc.

I think the user was more interested in building the app locally more than installing the finished version, which is a legit issue when trying to build it to contribute to it.

> If your distribution does not provide Akira packages, consider switching to one that does (e.g. FreeBSD).

While we don't offer direct support for all the distros, it's not really nice telling users to switch to another one.
