### ISSUE TITLE
Add your stripe key to appdata

### ISSUE THREAD

**Issue by danrabbit** [akiraux/Akira#630]
In the new version of AppCenter Dashboard, we're no longer modifying your appdata before publishing, so you'll need to add your stripe key to appdata.xml to continue to monetize your app in elementary OS 6

For your convenience, your public stripe key is:
`<value key="x-appcenter-stripe">pk_live_515yF9YDvXGakAYGJ74PQwmIwxs6xQrm0q0ULEAYO6vZyzsTIaOI40ZtDYj6qUGq6sjzCgwd25VQ4REbJob6pkB9r00tU1lgu6W</value>`

**Comment by albfan** [comment]
Thanks!, Really appreciate to inform us on this.

Any further details on monetize apps? Not sure if important here, but I help several open source project to release on flatpak and the monetization was an important concept to explore.

I know flatpak has some kind of API around that, but is the store (like flathub or elementary) which needs to provide implementation. Am I right?

**Comment by danrabbit** [comment]
@albfan Yes, so Flatpak does actually have a concept called "authenticators" that is essentially a flatpak app that gets automatically downloaded from the server to facilitate payments. We're not yet using authenticators for AppCenter. We still need to build that for our remote. In the future when we're using authenticators, you won't need to provide your stripe key in appdata since it will be linked on the server.

For now, we're still doing payments from inside the AppCenter client itself, which is why the stripe key needs to be present in appdata
