### ISSUE TITLE
Licensing query: GPLv2+ or GPLv3+?

### ISSUE THREAD

**Issue by Conan-Kudo** [akiraux/Akira#65]
It looks like Akira includes the GPLv3 license in `COPYING`, but the source files indicate that this is a GPLv2+ project.

There are two options here:
* Swap the COPYING file to match the terms the source specify. Here's [the license file for GPLv2](https://www.gnu.org/licenses/gpl-2.0.txt).
* Upgrade all the source files to GPLv3+ terms.

Personally, I'd rather you do option 1, but either option works.

**Comment by Alecaddd** [comment]
Thanks for the heads up, we will take a decision and fix this issue.

**Comment by dataminion** [comment]
Hey I came to post this issue as well. The waters are also made murky by the fact that github recognizes the license text and give a GPLv3 summary. Would also recommend changing the "COPYING" file title to the slightly more canonical "LICENSE" 

closing this issue via PR would also "merge" my excitement about this idea with my willingness to contribute to the kickstarted and clear up all "conflicts" I might have about if this is a real deal or not... #gitpuns

**Comment by Conan-Kudo** [comment]
> Would also recommend changing the "COPYING" file title to the slightly more canonical "LICENSE"

This part actually _really_ doesn't matter (`COPYING` has been in use slightly longer than `LICENSE` as a distribution text file for rights and rules about [re]distribution), but if you want to change it, you could...

**Comment by dataminion** [comment]
That was more of an aside I was mostly +1'ing your initial comment. As you point it out I think you are right vis a vis COPYING vs LICENSE... github default suggestions have made me lazy. 

I'd be happy to make some of those file comment changes you mention does the project have a contribution disclosure/policy yet?

**Comment by dataminion** [comment]
I noticed some of the files also reserve all copyright for @Alecaddd is there an intention/desire to remove those and also move the project as a whole to more of a "project space" vs hosted on a user account

**Comment by Conan-Kudo** [comment]
Copyright ownership is by default all rights reserved to him as he created the code. However, every code contribution automatically has unique copyright by those people. Those "All rights reserved" statements don't do anything meaningful after copyright has become distributed.

**Comment by dataminion** [comment]
so thats fair. I'm no uber contributor but the few projects I have posted to that are trying to or have moved past the guy in the basement phase have a "release of liability" form or statement that developers sign or agree to with when they merge which releases all copyrights from individuals to the project as a whole. 

This prevents committers from later using their contributions to sabotage and invalidate the licensing agreement.

**Comment by dataminion** [comment]
My understanding from the few interactions I have had with IP practitioners has been the opposite of your comment about copyright. In North America a copyright associated with software can often be more powerful than a patent. One of the reasons that cases of true copyright violation are not often discussed is because they are very one sided 

guy everyone liked at first but who later suddenly leaves the project under hostile circumstances: "they used the code i wrote that clearly had my copyright at the top, they admitted this was true in a deposition"
judge: "motion for summary judgement granted"

**Comment by Alecaddd** [comment]
I'm currently upgrading all the licenses to GPLv3.
