### ISSUE TITLE
Minimum window width cramps title unnecessarily 

### ISSUE THREAD

**Issue by ChildishGiant** [akiraux/Akira#650]
## Expected Behavior

The default window makes the "untitled" text overflow when there is plenty of room for it. The title should ge readable when there's room.

## Current Behavior

https://user-images.githubusercontent.com/13716824/129959780-24e6864e-54d0-4a44-af6e-56811b5fd844.mp4

## Possible Solution
I guess lower the padding around the title

## Your Environment (for bugs)

```
Linux elementary-os-desktop-39fa46e2 5.11.0-25-generic #27~20.04.1-Ubuntu SMP Tue Jul 13 17:41:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
NAME="elementary OS"
VERSION="6 Odin"
ID=elementary
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS 6 Odin"
LOGO=distributor-logo
VERSION_ID="6"
HOME_URL="https://elementary.io/"
DOCUMENTATION_URL="https://elementary.io/docs/learning-the-basics"
SUPPORT_URL="https://elementary.io/support"
BUG_REPORT_URL="https://github.com/elementary/os/issues/new"
PRIVACY_POLICY_URL="https://elementary.io/privacy-policy"
VERSION_CODENAME=odin
UBUNTU_CODENAME=focal
```
- Akira Version: v0.0.16 - alpha (appcenter)

**Comment by Alecaddd** [comment]
Fixed by #721
