### ISSUE TITLE
Menubar could be more compact

### ISSUE THREAD

**Issue by sr229** [akiraux/Akira#66]
Based on the UI mockup, I believe we can make the menu bar more compact by removing the icon at the left altogether and reducing the size (I believe there's just too many space in there that doesn't bode well), or have the icon in the left side small but clear enough to allow a compact menu bar. Some programs like Gravit Designer has some compact menu bars which overall looks cleaner than a large menu bar

**Comment by Alecaddd** [comment]
Thanks for the suggestion and your interest in Akira.
The UI mock-up is gonna be replaced soon by some accurate prototype which will represent the look of the app with higher fidelity.
Many tools have been already incorporated and moved around to save space and improve the usability.
Cheers

**Comment by Alecaddd** [comment]
Closing this as it's out of scope based on the recent UI of the app.
Here's a preview:

![headerbar-labels](https://user-images.githubusercontent.com/2527103/53468504-5bc3f480-3a0f-11e9-84ea-596963df236b.png)
