### ISSUE TITLE
executable ?

### ISSUE THREAD

**Issue by movingelectrons** [akiraux/Akira#670]
Spent the last two hours installing dependecies and stuff, finally got ninja & sudo ninja insall working.  I think... there are no more errors reported and everything looks to be okay... but, I do not see any executable?  how do you start akira from the command line?

**Comment by Alecaddd** [comment]
It's in the `src/` folder.
After running `ninja`, you can launch it with `./src/com.github.akiraux.akira`

**Comment by LucileDT** [comment]
@Alecaddd do we have a documentation explaining how to start Akira?

**Comment by Alecaddd** [comment]
> @Alecaddd do we have a documentation explaining how to start Akira?

Now we do :smile: 
I just update the README.

**Comment by LucileDT** [comment]
The full procedure to launch the app can now be found here: https://github.com/akiraux/Akira#compile--run :slightly_smiling_face:
