### ISSUE TITLE
goocanvas-3 dependency not available for most distros.

### ISSUE THREAD

**Issue by tobealive** [akiraux/Akira#689]
I would like to install Akira by compiling it from the source to use dev branches. 

Unfortunately it's not possible to build Akira (also the master branch).   As far as I can tell, the goocanvas-3 dependency is not available on Debian and Ubuntu based systems, so it's impossible to build. Its looks like the goocanvas-2.0 is the exact same up to date package but with another naming.

Is there a way to work around that, so I can install it from source? For example, by editing the installation files, so they look for the available package, and how would this be done?

With the new popos release, I switched from arch to pop and will keep it for some weeks. I know the goocanvas package availability wasn't a problem on arch.

`Run-time dependency goocanvas-3.0 found: NO (tried pkgconfig and cmake)`

**Comment by giacomoalbe** [comment]
Hi @tobealive, 

I think the most viable solution is to try to build from source the `main` branch. 

We are working at a complete rewrite of the underlying architecture, specifically the Canvas module, and the first thing that was done was to replace (completely rewrite, actually) the GooCanvas library with a custom made Vala module. 

So if you try to build the `main` branch (which is the main development branch at the moment), you should be able to compile without problems. 

If you want some more guidance on the process, I can help you in the Matrix channel.

**Comment by Alecaddd** [comment]
We're dropping goocanvas and we're not working on the `master` branch anymore.
All future development is focused on the `main` branch, which needs a lot of work to bring it back to features parity with `master`.

**Comment by tobealive** [comment]
Thanks for the quick reply and info. The main branch works!
