### ISSUE TITLE
Dark Theme not working

### ISSUE THREAD

**Issue by Odin000** [akiraux/Akira#702]
Dark theme not working at least on Pop!_OS 21.10

**Comment by Alecaddd** [comment]
I guess you installed via flatpak.
If that's the case, the issue with dark theme is that the elementary OS dark theme variation is not available in flathub yet.
I think you can solve this temporarily by installing Adwaita Dark via flatpak `flatpak install org.gtk.Gtk3theme.Adwaita-dark`, which will fall back to it.
But this is mostly an issue with elementary OS and flathub.
