### ISSUE TITLE
Suggesting Translation (Kurdish Language)

### ISSUE THREAD

**Issue by petrichor-494** [akiraux/Akira#715]
- Akira Version: v0.0.15 - alpha
- OS Info: Zorin OS 16.1

**Hello,** 
I would like to suggest a translation. I want to have the Kurdish language (Sorani) in this project and I am ready to work on it.

**Regards,**
Aga

**Comment by Alecaddd** [comment]
You can find the translatable files in the `po/` folder and you can contribute with a PR.
