### ISSUE TITLE
[Flatpak] org.gnome.Platform version 40 is EOL

### ISSUE THREAD

**Issue by teohhanhui** [akiraux/Akira#716]
## Expected Behavior
N/A

## Current Behavior
N/A

## Possible Solution
Upgrade to `org.gnome.Platform//42`

## Steps to Reproduce (for bugs)
N/A

## Context
> The GNOME 40 runtime is no longer supported as of March 21, 2022. Please ask your application developer to migrate to a supported platform.

## Screenshots of the Problem
N/A

## Your Environment (for bugs)
N/A

- Akira Version: N/A
- OS Info: N/A

**Comment by Alecaddd** [comment]
We follow the elementary SDK.
Once that updates to v7, we will migrate.
