### ISSUE TITLE
Suggesting translation - Dutch Language

### ISSUE THREAD

**Issue by lukelane1984** [akiraux/Akira#725]
**Good day**

I would like to spend some of my time translating Akira into the Dutch language.
I don't have that much free time, so I might have to share the load with another translator,
but I'd like to contribute.

I have some prior experience, I'm an official volunteer translator for Valve,
and I have translated a few Android apps from English to Dutch.  

- Akira Version: v0.0.16 - alpha
- OS Info: Garuda Linux KDE and Ubuntu Budgie 22.04

Kind regards,
Luke Lane

**Comment by Alecaddd** [comment]
You can find the translatable files in the `po/` folder and you can contribute with a PR.
