### ISSUE TITLE
Unir, interceptar Formas incertadas

### ISSUE THREAD

**Issue by cz9dev** [akiraux/Akira#738]
No deja unir, interceptar las formas
- Akira Version: v0.0.16 - alpha
- OS Info: Linux Mint 21 x86_64

**Comment by Alecaddd** [comment]
English, please

**Comment by cz9dev** [comment]
Sorry, in English
akira does not allow joining, intercepting shapes

**Comment by Alecaddd** [comment]
It's not implemented yet
