### ISSUE TITLE
IRC/Rocket.Chat/Whatever

### ISSUE THREAD

**Issue by thefoxie** [akiraux/Akira#74]
Hey, I'd tried to build Akira about 6months ago and seen no progress for many months. I must admit I was sceptical. Anyway, I would like to join the party. I think there should be open issues for missing features and some kind of communication service for devs. 

Also, wouldn't be better to stick with pure gtk? I know granite has some extra features, but it could be kept as simple and clean as much as it can be. From this point of view, granite is just another dependency, which is sort of bounded to Elementary OS.

EDIT: I see the Projects tab. K. I will take a look.

**Comment by Alecaddd** [comment]
Hi, thanks for your interest in Akira.
I was super busy in managing the Kickstarter campaign, creating high fidelity UI mock-ups, and setting things up for the other devs, so, apologies for the lack of updates in this repo.

I'm currently going through the issues and creating detailed tasks and issues targeting v1. Check the Projects page and Wiki, which we will use as a single source of truth to keep track of what Akira will look and how it will behave.

Regarding Granite, we don't see the problem with it. Granite is just a collection of handy Gtk Widgets that helps us in implementing some features without the necessity of coding it. Granite will be baked inside Akira once released as flatpak and snap, so it won't be a problem.

Cheers
