### ISSUE TITLE
Inactive project

### ISSUE THREAD

**Issue by aitor-gomila** [akiraux/Akira#744]
Last commit was 3 months ago, last release was for Odin 6. Is the project still active? Because the software looks promising

**Comment by albfan** [comment]
Probably implement any of the goals in 0.1.0 milestone https://github.com/akiraux/Akira/milestone/1

**Comment by aitor-gomila** [comment]
What do you mean? You are busy but accept PRs? Personally I have work to do but might be able to help a bit :-)

**Comment by LucileDT** [comment]
@aitor-gomila You may want to open a [Discussion](https://github.com/akiraux/Akira/discussions) instead of an issue
