### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by KevDoy** [akiraux/Akira#749]
Just wanted to open the discussion here, is this project alive? I haven't seen much if any movement in quite some time. Would love some insight into what the status is.

**Comment by cz9dev** [comment]
Me llamo mucho la atención este proyecto, pero lo veo detenido, quisiera igual saber el estado del mismo. ¿Siguen desarrollándolo?, o ¿está descontinuado?

**Comment by hblamo** [comment]
I too am interested in the status of this project.

**Comment by albfan** [comment]
I would day is stalled.

@Alecaddd might have more info

**Comment by JohnDumpling** [comment]
He last responded on Matrix (April 9) about planning to rewrite the app in Rust, but no further info so far. I assume it's a lack of motivation or time.

**Comment by KevDoy** [comment]
I reached out to Alessandro some months back just to connect and chat and never heard back. I did mention the project. I don't see this project going anywhere right now. I think "Stalled" is probably a good way to frame it.

**Comment by LucileDT** [comment]
Alessandro is currently working for Mozilla if I remember well, I suppose he doesn't have enough free time to work on Akira for now.

**Comment by Alecaddd** [comment]
Putting more time back into this during weekends.
You can follow the progress here: https://github.com/akiraux/Akira/projects?query=is%3Aopen
