### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by mfru** [akiraux/Akira#764]

**Comment by PlatonB** [comment]
Maybe attempt a new crowdfunding campaign?

**Comment by mfru** [comment]
Sorry, I don't see how that is an answer to my question.

**Comment by PlatonB** [comment]
@mfru It was a proposal to the Akira developers to solve the crisis.

**Comment by mfru** [comment]
As far as I know at least one of the devs is working in Thunderbird at the moment, so they may not have enough time even if the funds were there

**Comment by Alecaddd** [comment]
Hello, thanks for your interest in Akira.
The project is not abandoned but it's in a bit of an hiatus.
I work on it from time to time during the weekend, and I'm currently exploring a new Rust base to make ti faster and remove the bottlenecks that caused development slow down.
https://github.com/akiraux/Akira/tree/rust-alpha-0.0.1
