### ISSUE TITLE
Akira doesn't start, missing libthai package

### ISSUE THREAD

**Issue by lovemoebius** [akiraux/Akira#80]
I wanted to test out Akira since it seems like it has a lot of potential, unfortunately when trying to start it I receive this error:

> akira: /tmp/.mount_Akira.dbs5vJ/usr/lib/libthai.so.0: version `LIBTHAI_0.1.25' not found (required by /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0)

So I went to install libthai, but apparently it's already installed, just a newer version:

> libthai0 is already the newest version (0.1.28-1).

I don't think this is supposed to happen, but let me know if I'm doing something wrong.
Good luck with the development!

**Comment by albfan** [comment]
@lovemoebius you can try https://github.com/akiraux/Akira/tree/wip/albfan/flatpak and run in sandbox under flatpak. If you use GNOME Builder it should clone build and run in no time

**Comment by Alecaddd** [comment]
Akira is not out yet, so broken builds and issues are normal.
You can use the flatpak created by @albfan if you want to test it, but I recommend waiting for an official alpha release before creating bug reports.
