### ISSUE TITLE
Provide a more detailed roadmap/gameplan

### ISSUE THREAD

**Issue by Brekmister** [akiraux/Akira#82]
I just wanted to point out that the objective isn't really specific here yet. Do we have a plan for the individual features, shapes and, tools that Akira will use when it comes out with v1.0? How can we achieve in building those? How can we make sure that we don't stray off from the solid vision that we have and provide a more solid picture for developers who want to contribute?

I am not talking just the vision but, the goals and tasks that leads up to it.

Does anyone understand what I am talking about?

**Comment by Alecaddd** [comment]
Hi, thanks for your passion and interest in Akira.
Everything you said makes sense and it's a task I have in my constantly growing to-do list.

The short answer is, "A proper roadmap with dedicated issues, milestones, and goals is coming soon".

To be a bit more specific, we're currently focusing on the canvas library, which is the core of Akira and without that solid starting point, it's not recommended defining features and sections and let other developers work on those.
You can keep track of what we're doing in this repo: https://github.com/akiraux/interactive-goocanvas

In terms of Akira roadmap for version 1, the Wiki and the Projects page of this repo will be used for that purpose. As I said, I didn't have time to write down everything and those sections are still a WIP.
Approximately, the canvas work will be somewhat completed in the next 2 weeks, and after that, we will start working on Akira.
At that point, you will start seeing proper issue reports and tasks popping out in those sections.

You can take a look at the various Projects which will cover the basic functionalities for version 1: https://github.com/akiraux/Akira/projects

And the wiki is getting slowly populated with descriptions and visual references of how Akira will behave: https://github.com/akiraux/Akira/wiki
