### ISSUE TITLE
[Request] Support pressure sensitivity brush drawing from tablet pens

### ISSUE THREAD

**Issue by terndrup** [akiraux/Akira#84]
So I don't know if you guys have considered this, but if would be great to see akira have support for free drawing with something like a wacom tablet.

What's essential for such a feature is to support pressure sensitivity (i.e. change the brush thickness based on pen sensitivy reading).

For example for wacom in Adobe Photoshop:

"One of the most significant benefits is the recognition of pressure sensitivity in the Wacom pen. All tools that leverage the Brush Engine can take advantage of pressure sensitivity"

That would be an amazing feature to have!

**Comment by Alecaddd** [comment]
Thanks for your request, but unfortunately this is something completely out of scope for us.
We won't implement a brush engine as Akira will be focused on UI and UX mockups, all vector based.
Cheers.

**Comment by terndrup** [comment]
That's fair enough. I guess I'm hoping Akira will eventually transition into a full replacement for both InkScape and GIMP in the long run \o/

**Comment by abienz** [comment]
Hi @terndrup unfortunately they're tools for a completely different purpose. Akiras goal has a much tighter focus, UI design.

If it grew into replacements for GIMP and Inkscape it would lose this focus and become a jack of all trades and master of none. The code base would probably be a nightmare too! ;)
