### ISSUE TITLE
Patreon link in README goes to wrong (?) campaign

### ISSUE THREAD

**Issue by velovix** [akiraux/Akira#85]
The link in the README goes to https://www.patreon.com/alecaddd, which I believe is a personal Patreon for one of Akira's developers. Shouldn't it go to https://www.patreon.com/akiraux instead? According to the alecaddd Patreon it is partially to help fund Akira development, but it's also to fund other things like YouTube tutorials as well. I'm sure they're great tutorials, but I'm personally interested in funding Akira!

**Comment by Alecaddd** [comment]
I launched the Patreon for Akira yesterday and I forgot to update this link.
Doing it now
