### ISSUE TITLE
Bake the elementary OS style and icons in every build system

### ISSUE THREAD

**Issue by Alecaddd** [akiraux/Akira#93]
To maintain visual consistency and control the outcome of the application, we should implement the elementary OS stylesheet and icons in every build systems:

- Flatpack
- Snap - related to #70

**Comment by albfan** [comment]
We relay on elementary icons without pairs on Adwaita theme (See #99) so I think there's no point in cover this with patches like  https://github.com/flathub/com.github.cassidyjames.dippi/blob/master/elementary-theme.patch

![akira-flatpak-builder](https://user-images.githubusercontent.com/220968/53798775-35371980-3f39-11e9-8caa-b1deace27b14.gif)

Anyway I can be wrong and there's another way to do it.

If you see this ok, flatpak should be done. About snap I will try to follow this on #70

**Comment by bilelmoussaoui** [comment]
We can hardcode the theme on the source code but that will just break things. What we can do is ship all the icons. 
Regarding the GTK hackish thing called themes, for now, there's a Flatpak base app that will allow us to use the latest eOS GTK theme. We will switch to eOS runtime once out.

**Comment by Alecaddd** [comment]
@bilelmoussaoui that sounds perfect. I'm honestly more concerned about the icons rather than the theme. If we can avoid having missing icons, or even icons with a completely different style/abstraction, it'd be great.
